### ISSUE TITLE
Widget Player and colors update for Wiget Note 

### ISSUE THREAD

**Issue by Livio78** [zobnin/aio#10]
Hi, is it possible in the next AIO LAUNCHER update, in the Music Player Widget if the singer name and song title are too long to make them scroll without being truncated? Is it also possible to add more colors to the Notes Widget? Thank you

**Comment by zobnin** [comment]
Scrolling text is a very bad idea for the interface. There will never be anything like that in the AIO Launcher. More colors would be an unnecessary complication of the interface.
