### ISSUE TITLE
App folders in "My apps" widget

### ISSUE THREAD

**Issue by Rainerr123** [zobnin/aio#101]
On a traditional launcher you'd have a mix of apps and folders, I think it would be very useful to be able to have app folders in the "my apps" widget.
I'm aware there's already app folders but being able to have folders and individual apps on one line would keep it compact and improve functionality.
I only have use for 1 or 2 folders and having a whole widget just for 2 folders is un-tidy and not worth it

**Comment by zobnin** [comment]
I don't want to mix entities. It seems to me that if you need just one or two folders, you might not actually need folders. The second widget, either My Apps or App List, would be perfect for you.
