### ISSUE TITLE
Add the possibility to have titles only on specific/wanted widgets

### ISSUE THREAD

**Issue by RaffaeleBianc0** [zobnin/aio#102]
**Is your feature request related to a problem? Please describe.**
I love most widgets without their title.
But i am using 4 different text widgets (quote of the day, news on 2 RSS feeds, etc.), and sometimes it would be more clear to know the title.

**Describe the solution you'd like**
I'd like a switch to enable the title by widget.

**Comment by zobnin** [comment]
his is quite a significant complication of the settings (I would have to add about 30 settings), and it would be confusing. Therefore, my answer is no.
