### ISSUE TITLE
NFC Icon missing

### ISSUE THREAD

**Issue by jk1526** [zobnin/aio#103]
The NFC Icon in the control panel randomly disappears, if you toggle the colours it sometimes reappears but not always.

Behaviour is random.

**Expected behavior**

**Screenshots**
![Screenshot_20240113-110023.png](https://github.com/zobnin/aio/assets/50033284/eb8886c7-018e-4fa4-a795-04aa99585842)

**Smartphone Pixel 7 Pro running Android 14 Jan security patch.
AIO v 5.0.0-beta7 (902907)

This has happened on previous versions.

**Comment by zobnin** [comment]
Too little information. What does "disappears" mean? Does the icon completely vanish or does it seem to become invisible? Where should it be on your screenshot (indicate next to which icon)? What firmware are you using? Stock or custom? Do you have root privileges on your device?

**Comment by jk1526** [comment]
Definition of 'disappear ' no longer visible!  The icon is not there in any part of the control panel. The icon is available in the control panel settings in AIO settings though. I have it normally after Bluetooth icon, third from left. Am running stock firmware , with root. A reboot brings the icon back. It is random so unable to get a logcat.

**Comment by zobnin** [comment]
Apparently, for some reason, AIO Launcher considers that your phone doesn't have an NFC chip. On my Pixel 6a (Android 14), there is no such issue, so the root of the problem might lie either in the hardware or in the settings of your phone. Please reiterate: does your phone have root privileges? Are there any modifications installed, such as Xposed or Magisk modules?
