### ISSUE TITLE
Support adding multiple 1x1 widgets on a single row of screen space

### ISSUE THREAD

**Issue by barretobrock** [zobnin/aio#104]
**Is your feature request related to a problem? Please describe.**
Currently if I add a 1x1 widget (In my case, a temperature sensor for a Home assistant entity), it takes up the entire "row" of screen space. This means that the widget extends on both right and left to take up the whole row while the actual information contained in the widget remains in the center of the row. The result is a row with large, blank spaces on both sides. 

**Describe the solution you'd like**
It would be nice to have the option to add multiple 1x1 widgets to a single row so that screen space is not wasted. Whether this is done via holding & dragging the new widget over or via the widget config menu, doesn't seem to be a big difference to me as a user of that feature.

**Describe alternatives you've considered**
Adding a bunch of 1x1 widgets at the bottom of my screen so I can access them without most of the top of my screen being wasted by blank space. It works, but it's just a nuisance.

**Additional context**
Attached screenshot with areas of concern marked in red.![signal-2024-01-19-07-15-51-283.jpg](https://github.com/zobnin/aio/assets/8731386/673d65b9-eb7f-4a53-966c-2b3d97bb1519)

**Comment by zobnin** [comment]
There are specific reasons why it's not done this way. One of them is that the ability to add widgets horizontally would complicate desktop management. Perhaps in the future, I'll be able to find a simple and elegant solution to this issue.

**Comment by barretobrock** [comment]
That makes sense, thanks for explaining!

**Comment by mj-sson** [comment]
Check out the new "Widgets Container" widget in AIO 5.5.0 😀

**Comment by barretobrock** [comment]
I've applied it and it looks amazing! Thanks again!
