### ISSUE TITLE
Home Screen unresponsive 

### ISSUE THREAD

**Issue by cbworksdev** [zobnin/aio#106]
**Describe the bug**

**To Reproduce**
Sometimes the home screen is unresponsive to user feedback. The system gestures will still work, I am able to swipe from the bottom to change apps. 

Im trying to find a pattern to when this occurs, and might occur when I receive a tick tick notification. 

**Expected behavior**
For the home screen to allow me to interact with it. 

**Screenshots**
![Screenshot_20240212_164717_AIO Launcher](https://github.com/zobnin/aio/assets/69275805/55f1e41a-2f3f-497f-b296-1259053cccf8)

When this happens, the keyboard switcher will remain at the bottom along with an arrow. It will only show from the home screen. If I switch apps, everything functions as normal inside that app.

**Smartphone (please complete the following information):**
 - Device: s23 ultra 
 - Android version: Android 14
 - AIO Version: 5.0.0 (901533)

**Additional context**

**Comment by zobnin** [comment]
Not launcher problem. See last question in the FAQ: aiolauncher.app/faq.html
