### ISSUE TITLE
Expenses widget -edit categories & budgets

### ISSUE THREAD

**Issue by Lorestan00** [zobnin/aio#107]
**Is your feature request related to a problem? Please describe.**

Would be useful to be able to edit categories add in own options

Have ability to set budget so you can see how much money you have left to spend

**Describe the solution you'd like**

In category section amend existing categories and add new ones. Perhaps move order so it's easier to select option

Add option to add a monthly budget figure 

**Describe alternatives you've considered**

**Additional context**

**Comment by zobnin** [comment]
I don't think that adding custom categories is a good idea. If the existing 150 categories are not enough for you, then 1500 won't be enough either.

**Comment by Lorestan00** [comment]
It's the not volume that the issue. You could have a million it's what the options are! E.g. you have a 'Fun' ..okay and then the subcategory 'New technology ' which might not be everyone's idea of fun but more common things like cinema or theatre are not present. 

In the categories widget you allow for users to create their own and it's probably less necessary as the options broadly cover most apps but it's a good option to have. Just suggesting replicating the same functionality
