### ISSUE TITLE
When an app is uninstalled in playstore, the icon stays in the widget (but replaced by an "android" icon) pointing to the uninstalled app in the playstore.
Maybe done on purpose or not ?

### ISSUE THREAD

**Issue by Madydri** [zobnin/aio#11]
![IMG_20220306_202614.jpg](https://user-images.githubusercontent.com/70443803/156939089-0499a2ee-4b9b-46dc-808b-bf995ad9d90b.jpg)

**Comment by zobnin** [comment]
Please don't place issue text in the title
