### ISSUE TITLE
Widget Stacks

### ISSUE THREAD

**Issue by Lorestan00** [zobnin/aio#111]
**Is your feature request related to a problem? Please describe.**
There are lots of useful AIO widgets never mind android ones so you can end up with a long list of widgets. This means you can be scrolling up and down quite alot

**Describe the solution you'd like**

I'm proposing introducing widget stacks like in Apple and Samsung software, as well as android launchers such as Action, Smart and Niagara launchers which allows for multiple widgets to be swiped to cycle through them either vertically or horizontally. 

This will allow for users to create stacks for example frequent apps and my apps together or perhaps finance, expenses and bitcoin etc. 

Massive space saver and much more efficient.

**Comment by zobnin** [comment]
AIO Launcher already has features that allow you to save space. If you want to keep a widget on the screen permanently, you can minimize it. If you only need the widget from time to time, you can use the search to quickly view the widget's contents, or the side menu (but search is much faster and more convenient).

Widget stacks are not a solution to the problem; they are just another "cool thing" that Apple invented to solve problems it created itself. They once brought us the trend of wastefully uncomfortable desktops with a grid of icons and a dock.

**Comment by zobnin** [comment]
closing

**Comment by zobnin** [comment]
closing

**Comment by Lorestan00** [comment]
Minimising is just adding extra steps. Widget stacks isn't a cool idea it practically allows for more widgets on screen. There is a premium on space on phones. This is why so many launchers have adopted it. 

Is there any point suggesting anything?  It feels like a waste of time. I've never seen you take on anyone's ideas. Computer says no to everything
