### ISSUE TITLE
Currency Conversion: TWD not working properly

### ISSUE THREAD

**Issue by dkHugh** [zobnin/aio#112]
In the currency conversion widget, when converting to, or from TWD with any other currency, it would display for example "1 USD=-1.00 TWD" or "1 TWD=-1.00 USD".
It is regardless of my preferred currency setting. Other currencies seem to convert normally, reinstalling AIO did not help. 
 

 - Device 1: Google Pixel 6a
 - Android version: Android 13
 - AIO Version: 5.1.0

- Device 2: Cat S22 FLIP
- Android version: Android 11 Go 
- AIO Version: 5.1.0
![Screenshot_20240228-125200](https://github.com/zobnin/aio/assets/25021195/2d34406f-4365-4d56-9af7-beefe90d148c)

**Comment by zobnin** [comment]
Install latest version please
