### ISSUE TITLE
Things that don't work properly

### ISSUE THREAD

**Issue by Peaulixs** [zobnin/aio#114]
Rearranging category rankings using AI does not work with premium subscription, it gives a Timeout message

Often when I search for an application on my device with the AIO search button nothing happens when I press the icons I have to close the Google keyboard for pressing the icons to work.  

When I do a search with the AIO search button and long press it to search in an application, Play store returns to the ebook search results page and not to the applications page,  chrome and Reddit gives a message "unable to open" Gmail and Google returns to the launcher home page.

I use a Pixel 7 Android 14

Sorry for bad english

**Comment by zobnin** [comment]
Please post bug reports using template. One problem by bug report.

Regarding your questions:

1. Yes, it appears that when the number of applications exceeds a certain threshold, ChatGPT stops generating correct responses. I will look into it.

2. This does not seem like a launcher issue. Most likely, some application is just overlaying the screen. I can't say more without additional data, which was in the template. Try using a different keyboard.

3. Not all applications can properly handle search queries. There's nothing I can do about this except possibly remove this function from the launcher.

**Comment by zobnin** [comment]
First problem is fixed in the latest version. Thank you.
