### ISSUE TITLE
Maps -blank screen

### ISSUE THREAD

**Issue by Lorestan00** [zobnin/aio#116]
**Describe the bug**
No map shows up. Big white space

**To Reproduce**
Added maps widget
Downloaded Great Britain map

**Expected behavior**
.

Expected to see the map of great britain

I've tried to redownload maps but no difference

**Screenshots**
![Screenshot_2024-05-18-20-08-28-77_c483b0a08a3d13961f22556f3195da20.jpg](https://github.com/zobnin/aio/assets/81394097/f5568a88-2c11-4ec1-9f60-f07b7180540b)

**Smartphone (please complete the following information):**
 - Device: open plus open
 - Android version: 14
 - AIO Version: 5.3.0-beta7 (903074)

**Additional context**

**Comment by zobnin** [comment]
It seems that your phone is incorrectly determining your location, which is why the map points to an area for which there is no map available. You can zoom out as much as possible to confirm this.
