### ISSUE TITLE
Shake Sensitivity Not Working

### ISSUE THREAD

**Issue by kylesoule** [zobnin/aio#119]
**Describe the bug**
Shake gesture sensitivity does not seem to be working. 

**To Reproduce**
1. Set shake sensitivity to 1/100, little to no movement triggers the gesture.
2. Set shake sensitivity to 100/100, little to no movement triggers the gesture, seemingly the same amount as 1/100.

**Expected behavior**
Reduce or increase shake sensitivity based on setting.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 5A
 - Android version: 14
 - AIO Version: 5.3.2-beta1 (903085)

**Comment by zobnin** [comment]
This is an old option that has never worked properly on all phones. Moreover, it is inconvenient. Therefore, I will remove it in future versions. Thank you.
