### ISSUE TITLE
The icon pack is displaying incorrectly

### ISSUE THREAD

**Issue by dw1405** [zobnin/aio#12]
![Screenshot_20220321-134936](https://user-images.githubusercontent.com/62808376/159336452-49c24d61-7e04-4771-9e25-45b3b9756c8f.png)
From Vera Icon Pack

**Comment by zobnin** [comment]
Can you explain exactly what the problem is

**Comment by dw1405** [comment]
In the second line of frequent apps, you can see the app numbers 3, 5, 6 with some strange shapes. It's supposed to look like this: ![Screenshot_20220323-083404](https://user-images.githubusercontent.com/62808376/159701382-e6980fe7-f2a6-4e3a-be37-37649604a50c.png)
It's the only icon pack (that I know of) with this problem so I'm not sure.

**Comment by zobnin** [comment]
Fixed
