### ISSUE TITLE
Tapping notification items shows task underneath, rather than opening app

### ISSUE THREAD

**Issue by Bookbabe** [zobnin/aio#120]
When tapping on notifications in the notification widget, the notification is replaced by an unchecked task from my calendar. Tapping the calendar task will then open the original notification app.

So normally I might have a text notification. If I tapped that notification, it would open my messages app to the text page. Instead, when I tap it it shows a checkbox with "take pill" -- a recurrent task I have set up in my calendar. This will happen no matter how many notifications I tap. These tasks typically show up as a banner notification but don't show up in the widget.

![Screenshot_20240531-014201](https://github.com/zobnin/aio/assets/171315764/92bfb968-9f9f-4aff-b6f7-6848ac135ccd)
![Screenshot_20240531-014156](https://github.com/zobnin/aio/assets/171315764/3c0ba176-28ee-4484-bff7-46b3360d3737)
![Screenshot_20240531-014143](https://github.com/zobnin/aio/assets/171315764/3b42b8b1-cdab-4574-baf4-f9ad49e4cbfa)

**Smartphone (please complete the following information):**
 - Device: Motorola Edge+ 2023
 - Android version: 14
 - AIO Version: 5.3.1 (901558)

**Comment by zobnin** [comment]
Yes, this is a change in the latest version of AIO Launcher. Now it can display complex notifications when clicked. Previously, it just showed "Empty." This is normal behavior. But as I understand it, you would like it to work differently? How?

**Comment by zobnin** [comment]
Ahhh. Sorry. I understand. You are talking about bug when UI from previous notification is showed in the other norifcation. It will be fixed in the next version. Thank you.
