### ISSUE TITLE
403 error, ChatGPT reorganize categories failure

### ISSUE THREAD

**Issue by aakast** [zobnin/aio#123]
**Describe the bug**

When pressing the button in the settings a 403 error is returned. Wrong API key in the backend? No more money on the balance at OprnAI?

**To Reproduce**

Press the button in settings

**Expected behavior**

Don't know what is expected, but I would assume it labels the apps.

**Screenshots**

**Smartphone (please complete the following information):**

Samsung Galaxy s23 Ultra
Android 14
AIO Version 5.2.4

**Additional context**

**Comment by zobnin** [comment]
Use latest version from Play Store
