### ISSUE TITLE
Can no longer add system widgets from the launcher

### ISSUE THREAD

**Issue by CaptainFrosty** [zobnin/aio#124]
**Describe the bug**
I have always been able to add widgets and shortcuts from the AIO UI but now it only shows the two shortcut menus. The only way I can add widgets is if I can share it from the app itself. 

**To Reproduce**
Long press search button
Tap add button
Only shortcuts appear to be added

**Expected behavior**
Normal widget menu

**Screenshots**

**Smartphone (please complete the following information):**

- Galaxy S22+
- Android 14/OneUI 6.1
- AIO Version: 5.3.4, I was on a beta but I downgraded

**Additional context**

**Comment by zobnin** [comment]
Open side menu, click on the bottom menu and choose Widgets
