### ISSUE TITLE
Adding events directly from Calendar vidget

### ISSUE THREAD

**Issue by ChibyX** [zobnin/aio#125]
Currently if you need to create calendar event, you can tap on one of existing events, then on calendar icon in top-right corner which opens calendar app and then add event. I think it would be easier to add button to widget which will directly open event creation interface. It could look like "+" icon in top-right corner of widget or "Add event" string in the bottom - like in Notes or Tasks widgets.

**Comment by zobnin** [comment]
I will add the option later. Thank you.

**Comment by zobnin** [comment]
Added to 5.4.1 beta version
