### ISSUE TITLE
Calendar list does not show up

### ISSUE THREAD

**Issue by c-moon-xxxx** [zobnin/aio#13]
After I've factory resetted my phone, AIO cannot pick any events from my calendar.
The permisson is already glanted but a calendar list is also empty in widget settings.

How can I fix this?

![Screenshot_20220429-030107](https://user-images.githubusercontent.com/58577127/165820152-6683e694-a494-4221-8238-79d77dea516b.png)

**Comment by zobnin** [comment]
You need to look for a problem not in the AIO Launcher. Obviously, if everything was working fine before resetting the phone, then the problem is in the phone settings. For example, you just forgot to turn on calendar synchronization or something like that.

**Comment by c-moon-xxxx** [comment]
Disabled and re-enabled all calendars, then it worked fine.
Thx a lot!
