### ISSUE TITLE
apps disabling from play store

### ISSUE THREAD

**Issue by KruinKop** [zobnin/aio#133]
**Describe the bug**

some apps keep disabling and thus disappearing from the app drawer on the right

**To Reproduce**

1. Go to play store
2. enable app
3. wait sokm time
4. see app disappearing from app drawer

**Expected behavior**

apps not disabling on their own, when switching to the default launcher, the app is still present.

**Screenshots**

**Smartphone (please complete the following information):**

 - Device: boox note air
 - Android version: 12
 - AIO Version: 5.4.2

**Additional context**

https://www.reddit.com/r/androidapps/s/s1QeZPLGGf
someone with the same problem

**Comment by zobnin** [comment]
How to enable app from play store?

**Comment by KruinKop** [comment]
No, the problem seems that apps keep disabling on their own from the launcher. When I switch to the default launcher I don't get this behaviour

**Comment by zobnin** [comment]
You don't understand. I asking you: show to enable app from play store?

**Comment by KruinKop** [comment]
![Screenshot_20241019-092356](https://github.com/user-attachments/assets/d907ec18-eb84-4df0-9387-c82fe29775c8)
![Screenshot_20241019-092441](https://github.com/user-attachments/assets/ca15c2e7-a7aa-4aae-ad95-f6fb1f6f9403)
![Screenshot_20241019-092501](https://github.com/user-attachments/assets/5f751152-b972-4790-a75e-4f19b3c60380)

**Comment by zobnin** [comment]
I didn't quite understand how to enable and disable apps in the Play Store. The screenshot didn't help me at all.
