### ISSUE TITLE
make opening recent notes and books possible from launcher

### ISSUE THREAD

**Issue by KruinKop** [zobnin/aio#134]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
on boox devices recent notes and books show up as a widget. selecting and touching a note for example opens the notes app instead of the note itself. It would be nice if this opens the note.

**Describe alternatives you've considered**

**Additional context**

![Screenshot_20241016-124517](https://github.com/user-attachments/assets/505f54ea-c55b-4aff-90f6-196110671b24)

**Comment by zobnin** [comment]
I have no control of how widgets works
