### ISSUE TITLE
Calendar widget: events with repetition are deleted without asking

### ISSUE THREAD

**Issue by alexjulien** [zobnin/aio#135]
**Describe the bug**

Using the Calendar widget, I tried to delete a specific repetition of an event. Instead of the "standard/expected behavior" of asking if I wanted to delete 
- this specific event
- all future events
- all events
all events got deleted. I understand this sits between a bug report and a feature request, but right now, what happened left me confused and annoyed.

**To Reproduce**

1. Create an event with repetitions in your preferred calendar app
2. Delete it using the Calendar widget

**Expected behavior**

Before proceeding to delete the event, AIO should ask what to delete, as specified in the description. 
As an alternative, the delete confirmation dialog  should warn that AIO will delete every instance of the event.

**Smartphone**

 - Device: Samsung Galaxy S24 Ultra 
 - Android version: 14
 - AIO Version: 5.5.1

**Comment by zobnin** [comment]
1. There IS confirmation dilalog before deleting event.
2. There is no concept of "different instances of an event"; there are recurring events, but it is still considered one event.
