### ISSUE TITLE
Week Calendar Event Text Blank

### ISSUE THREAD

**Issue by TheQwervy** [zobnin/aio#137]
**Describe the bug**
Sometimes the event text in the weekly calendar is blank

**To Reproduce**
Unsure

**Expected behavior**
Calendar event text is always visible

**Screenshots**
![Screenshot_20241217-111027~2](https://github.com/user-attachments/assets/c5dcb5ef-fdea-42bf-8f94-3dba2d42646a)

**Smartphone (please complete the following information):**
 - Device: Sony Xperia 5v
 - Android version: 14
 - AIO Version: 5.5.4

**Additional context**

**Comment by zobnin** [comment]
Obviously, the text exists and is most likely black in color. I need more details. What theme are you using? Could the problem appear after switching between day/night mode on the phone?

**Comment by TheQwervy** [comment]
I'm using a modified dark cards theme. I can see the text on every other day. Just not monday, I did not switch between day and night mode. My phone is permanently on night mode.

**Comment by zobnin** [comment]
Please try to use some standard theme and tell me how it works.

**Comment by TheQwervy** [comment]
Its weird, you're right. I changed text colour but none of my text colour
is black why would the calendar event text become black if most of my text
is set to white?

**Comment by TheQwervy** [comment]
I figured it out, when you set progress bar colour to pure white the current calendar event next becomes pure black. I think its overflowing into black for some reason. Any setting below pure white works fine

@zobnin I think that this colour overflow might be an actual bug that needs fixing

**Comment by zobnin** [comment]
Can't reproduce. It is something else.
