### ISSUE TITLE
Setting to Change Hold Length

### ISSUE THREAD

**Issue by TheQwervy** [zobnin/aio#138]
**Is your feature request related to a problem? Please describe.**
I occasionally don't hold buttons long enough to activate their hold function. I'm very used to 150ms hold activation length 

**Describe the solution you'd like**
A setting in the AIO settings that allows me to adjust the time of the hold activation length 

**Describe alternatives you've considered**

**Additional context**

**Comment by zobnin** [comment]
AIO Launcher uses standard android long press delay. It's unlikely there’s another person who would need this setting.

**Comment by TheQwervy** [comment]
Okay thanks. I'll find a way to tweak the android delay manually
