### ISSUE TITLE
A better way to minimize widgets

### ISSUE THREAD

**Issue by TheQwervy** [zobnin/aio#139]
**Is your feature request related to a problem? Please describe.**

The minimize/maximize button is too small and I often end up activating the pressing the function next to the min/max button. E.g. the monitor widget. Or missing it entirely

**Describe the solution you'd like**

A better way to min/max widgets. Maybe a larger button or bar. Something that's easier to click and doesnt activate other functions 

**Describe alternatives you've considered**

I tired using the swipe to the right gesture but that doesn't work for the conversations or notifications widgets 

**Additional context**

**Comment by zobnin** [comment]
There are three ways to fold widgets:

1. Tap on the title (preferred way of you often fold widgets).
2. Button in the corner.
3. Swipe action.

I really don't think that four way will solve somehing. Just use titles. It is a good way.

**Comment by TheQwervy** [comment]
I have titles disabled to save space. All I'm saying is make an option to
make the button in the corner larger

**Comment by zobnin** [comment]
I think you need to decide what’s more important: saving space or making folding convenient. Increasing the button size won’t help because it’s already large enough (it’s much bigger than the dot that appears on folding). A larger button will start overlapping the widget’s elements.

**Comment by TheQwervy** [comment]
Alright thanks for your fast replies! I really appreciate it

**Comment by zobnin** [comment]
Ok maybe I can expand button size slightly in the next version.

**Comment by TheQwervy** [comment]
That would be awesome! Thanks again for your help
