### ISSUE TITLE
Widget-Level Actions

### ISSUE THREAD

**Issue by antdking** [zobnin/aio#14]
Firstly, I love the uniqueness of this launcher. Been daily driving it for a couple of months now. 

**Is your feature request related to a problem? Please describe.**
Difficult to control actions on individual widgets/sections. 
Left handed user, unable to right the top-right corner of a widget without shuffling.

---

**Describe the solution you'd like**

Widget-level actions would add a lot of flexibility.
Something I do for my keyboard is adjust long-press down to 150ms.
Perhaps an action modifier could be added; "hover", then use a gesture which applies a widget-level action.
Other modifiers might be to hijack the swipe left/right widget action.

Examples
1. Hover on widget
2. Short swipe down
3. Widget unfolds

_akin to drawing shapes, but limited to 1 direction change for simplicity_
1. Swipe left, do not release finger
2. Change direction, swipe down
3. Widget unfolds

---
**Describe alternatives you've considered**
N/a

**Additional context**
- Left Handed, 1 handed user
- Pixel 6, have to shuffle phone in hand to use top + right-hand side of screen

**Comment by zobnin** [comment]
I find such complicated gestures unacceptable. That's why there's nothing more complicated in the Launcher than normal side-to-side gestures and simple actions like double tap.
