### ISSUE TITLE
Searching for category icons doesn't work

### ISSUE THREAD

**Issue by TheQwervy** [zobnin/aio#141]
**Describe the bug**

When I start typing to find category icons it hides a the icons

**To Reproduce**

1. Navigate: AIO settings - Categories - Edit Categories - edit a custom category
2. Select the icon
3. Start typing in the search box

**Expected behavior**

It should show the icons related to the search term instead of hiding a the icons

**Screenshots**

![Screenshot_20241217-133009.png](https://github.com/user-attachments/assets/373f63a1-8c92-4512-bdd7-501646bdafc8)

**Smartphone (please complete the following information):**
 - Device: Sony Xperia 5v
 - Android version: 14
 - AIO Version: 5.5.4

**Additional context**

**Comment by zobnin** [comment]
Confirmed. Will be fixed in the new version.
