### ISSUE TITLE
Side menu blank on pull-down

### ISSUE THREAD

**Issue by TheQwervy** [zobnin/aio#142]
**Describe the bug**

When I pull the sides menu down it shows nothing.

**To Reproduce**

1. Open the side menu
2. Pull it down

**Expected behavior**

I believe that pulling down the side menu is meant to show contacts or calendar however it shows nothing. Contacts and calendar are selectable in the bottom part of the menu. 

**Screenshots**

![Screenshot_20241221-121247~2.png](https://github.com/user-attachments/assets/217f797b-694a-41f0-9a5a-01c34313281a)

**Smartphone (please complete the following information):**
 - Device: Sony Xperia 5v
 - Android version: 14
 - AIO Version: 5.5.4

**Additional context**

**Comment by zobnin** [comment]
It works as intended becaouse it one handed mode to reach top list elememnts. Not menu or something like this.

**Comment by TheQwervy** [comment]
Ah I see, so what is it saying in the scripts under calendar and contacts
about "to select it, open the side menu and pullt it down"?

**Comment by zobnin** [comment]
Where is this messge?

**Comment by TheQwervy** [comment]
Aio settings - scripts - calendar/contacts - note

**Comment by zobnin** [comment]
It is obsolute info. I will change it.
