### ISSUE TITLE
AIO Settings Activity is lost when switching app

### ISSUE THREAD

**Issue by antdking** [zobnin/aio#16]
**Describe the bug**
When you switch to another app, there's no way to get back to the Settings activity.
Returning back to AIO takes you back to the homescreen

**To Reproduce**
1. Go to 'AIO Settings' 
2. Open 'Recent Apps' (OS level)
3. _Activity is lost here, note the Recent App shown is **not** AIO, but your previous app_
4. Press 'back'
5. You are taken back to the home screen

**Expected behavior**
To be taken back to the AIO Settings. 
Ideally, the Activity is also preserved in Recent Apps, so you can get back to where you left off.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6
 - Android version: Android 12 QRP `S3B1.220420.005`
 - AIO Version: 4.4.0-beta29

**Additional context**
N/a

**Comment by antdking** [comment]
Can you add a way to quickly copy the smartphone details from the app, to make reporting bugs easier?
I believe Github has a bit of flexibility with passing content through Url parameters for issues.

**Comment by zobnin** [comment]
Works as intended

**Comment by antdking** [comment]
Then please treat this as a feature request 😊

**Comment by zobnin** [comment]
In fact I just can't do it right now because of old android versions compatibility
