### ISSUE TITLE
Blur animation inconsistencies on App side panel

### ISSUE THREAD

**Issue by antdking** [zobnin/aio#19]
**Describe the bug**
Blur seems to apply then not unapply under certain circumstances

**To Reproduce**
1. Go to 'Home'
2. Swipe part way to open side panel, then release so it still closes
3. Blur applies on open, not removed on close

**Expected behavior**
Blur is applied on open, then unapplied when closed. 

Bonus feature request too: Might be worth transitioning in the blur as well (increase from 0-30% based on distance pulled).
It makes it less jarring on the eyes; subtle, but you still notice it for quick actions. 
I believe its supported with the Blur API, it was how the notification panel "bug" worked ;)

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - Android version: 12 QRP3
 - AIO Version: 4.4.0 beta 29

**Additional context**
Seems they removed showing taps on screencap
https://photos.app.goo.gl/txZUZEnbNBaFSVhJA

I've also had other behaviours present, such as blur unapplying on Latch Open.
Likely all related to the same code doing your state management though, so fixing one will end up fixing them all.
I can push a test build through it's paces if you want

**Comment by zobnin** [comment]
Already fixed. You need to update.

**Comment by antdking** [comment]
Cool, update not available yet; latest I have is 4.4.0-beta29.

Will force a check again later

**Comment by antdking** [comment]
Still present in 4.4.1-beta6

**Comment by zobnin** [comment]
You need next version :)

**Comment by antdking** [comment]
Largely functionally working for opening the side bar as of 4.4.1-beta8. 


A few minor inconsistencies:
- from an open sidebar; partially close, release to let it bounce back open => Blur is removed with the sidebar still open.

From a closed sidebar:
- Without lingering, swipe to the right from the edge; Blur is applied on TouchRelease, meaning there's no Blur for the transition until you have released your finger.

- partially open the sidebar, then release to allow the sidebar to bounce back. => Blur is applied when you release your finger, then removed when the sidebar Latches Closed.


Actions seem to apply the Blur fine.
Pressing the edge of the screen to cause the sidebar to unlatch: _then_ swiping right, the Blur works as expected.

**Comment by zobnin** [comment]
This feature will never work 100% well. That's why it's disabled by default and probably shouldn't have been added in the first place.
