### ISSUE TITLE
Add Presearch as a search option

### ISSUE THREAD

**Issue by bsteimel** [zobnin/aio#2]
I use presearch.org as my search engine of choice. I would like to request this engine be added to the options in Settings -> Search -> Web Search Engine.

i currently use duckduckgo here but would rather use presearch.

**Comment by zobnin** [comment]
I will no longer add support for exotic search engines. Practice shows that their API is unreliable (two examples: Qwant and StartPage, which at some point simply stopped working).

Perhaps in the future I will add the ability to add your own engines.

**Comment by zobnin** [comment]
AIO Launcher 4.4.0-beta13 now supports the connection of any search engine. To do this, you need to specify the address of the search query in the "Own search engine" option, replacing the search string with `%s`. For example:

```
https://google.com/search?q=%s
https://www.qwant.com/?q=%s
https://www.startpage.com/do/search?q=%s
https://engine.presearch.org/search?q=%s
```
