### ISSUE TITLE
Wrong dialer app selected

### ISSUE THREAD

**Issue by Nuube** [zobnin/aio#20]
**Describe the bug**
I installed a different dialer app (namely "Koler") from F-Droid. When I the dialer widget from AIO it does not start  the dialer app but displays a error message that I need to set the google dialer as standard dialer app.

**To Reproduce**
1. Install Koler 
2. Select Koler as standard dialer app in android settings
3. Start AIO with dialer widget
4.  Press the phone icon in the dialer widget

**Expected behavior**
Start Koler

**Comment by zobnin** [comment]
I don't see this problem on the Pixel 4a with Android 12. What phone do you have and what version of Android?

**Comment by Nuube** [comment]
I have a Pixel 4a with Android 12 as well. For some reason github does not allow me to attach screenshots here, otherwise I added it here.

**Comment by Nuube** [comment]
-- Now it works:

![img2](https://user-images.githubusercontent.com/25643142/173117954-b925df05-420a-4c6d-8fd8-3db0e33fc932.jpg)

**Comment by zobnin** [comment]
Official or custom firmware?

**Comment by Nuube** [comment]
Official

**Comment by zobnin** [comment]
I can't replicate this problem so I don't know how to fix it at this point.

**Comment by Nuube** [comment]
For me the root cause looks a bit like AIO opens the google phone app in spite of Koler, and the google phone app issues the error that in can only be used when it is set as being the standard app.

Is it to possible to get the information which is the standard phone app from the OS before opening the app, or does android select the correct app when called?

**Comment by zobnin** [comment]
AIO Launcher works exactly as you ask in the second paragraph. Therefore, when I choose Koler as a standard application for calls on my Pixel 4a Launcher launches it, not Google Dialer. So I see no issue there.

**Comment by zobnin** [comment]
BTW Check AIO Settings -> Dialer -> Dialer. It seems to me that you just forcibly selected Google Dialer in the settings of the launcher itself and forgot about it.
