### ISSUE TITLE
Ability to customise individual app widgets 

### ISSUE THREAD

**Issue by RajCodeLabs** [zobnin/aio#21]
There are some apps i have whose name are not related to the widget they're showing. Also some apps app widgets work excellent with the clean-up widgets feature, while others don't.

I wish there was a feature where you could change the header name of the widgets and also set the widget clean-up feature for specific widgets only.

**Comment by zobnin** [comment]
As for names: can you give me an example where the name does not match the essence of the widget itself?

As for the "cleanup widgets" option. This is an experimental option, not recommended for use at all.

**Comment by BuiltByRaj** [comment]
> As for names: can you give me an example where the name does not match the essence of the widget itself?
> 
> As for the "cleanup widgets" option. This is an experimental option, not recommended for use at all.

Sure, one of them is a local app that I use, another is this kwgt widget.

![IMG_20220702_080851.jpg](https://user-images.githubusercontent.com/44139208/176983796-6d186b38-dcb4-4c5f-9f25-3fff6c477498.jpg)

And thanks for the heads-up on the clean-up feature.

**Comment by zobnin** [comment]
Fixed in 4.9.0
