### ISSUE TITLE
Backup and restore seems no to include external android widgets (added with (Add Widgets")

### ISSUE THREAD

**Issue by Madydri** [zobnin/aio#25]
**Describe the bug**
When restoring after a backup the android - widgets that where placed are not present anymore

**Comment by zobnin** [comment]
It is normal

**Comment by zobnin** [comment]
A more detailed explanation: when you add a widget, the system allocates an ID for it and binds it to the application. When you reset the application, or install the application on another device to restore the backup later, these IDs will be lost.

**Comment by Madydri** [comment]
Thanks @zobnin for the explanation, I now better understand why it's no possible. Thanks 🙏
