### ISSUE TITLE
Frequent apps sort by most opened *in the last month*

### ISSUE THREAD

**Issue by maxfire2008** [zobnin/aio#26]
**Is your feature request related to a problem? Please describe.**
My frequent apps menu has a bunch of apps that I haven't used in ages

**Describe the solution you'd like**
Sorting based off of most opens in the last week and if it doesn't have that then sort by last month. (This could be customisable in a menu).

I imagine this could be implemented by keeping track of all the open times and counting back though them and then deleting all opens older than a year every month with a Cron job or similar.

**Comment by zobnin** [comment]
I agree. This is a problem that needs to be solved. For now you can use sorting by time of use. It should work for you.

**Comment by zobnin** [comment]
Just use sorting by usage
