### ISSUE TITLE
Landscape Mode & Categories / Save Position

### ISSUE THREAD

**Issue by Swap-File** [zobnin/aio#27]
If the "Apps menu style" is set to "Categories", and you select a category, and then go into landscape mode, I don't see any way to select a different category.

Potential Fix / Workaround: 

While "Apps menu style" is set to "Categories", turning off "Save Position" in App Settings only seems to reset the app menu's vertical scroll.  When the app menu closed it doesn't reset the category to "alphabetical".

If "Save Position" being turned off could also cause the the app menu category to reset "Alphabetical" on reopen, it could make landscape mode more usable.

**Comment by zobnin** [comment]
When you switch to landscape mode, a button with an up arrow appears in place of the category switching buttons. Pressing it causes the category switching buttons to appear.

**Comment by Swap-File** [comment]
Thanks, I did not see that.

Is "Save Position" not resetting the category to "Alphabetical" by design?  Or could that be an option?

**Comment by zobnin** [comment]
Yes. It is by design. But maybe it needs to reset. I will think about it.
