### ISSUE TITLE
Notes disappear after some time in order of when they were created

### ISSUE THREAD

**Issue by leliamesteban** [zobnin/aio#30]
**Describe the bug**

When I enable the Notes widget and create notes, they get deleted without me doing anything, after some time. They get deleted in order of when they were first created.

**To Reproduce**

1. Enable Notes widget

2. Create note

3. Create more notes. (I will investigate whether this step is necessary to reproduce the bug or if it happens even with only one note.)

4. After some time (a few days), the notes I created first disappear, while the notes I created more recently are there.

Note that I only ever created 4 or 6 notes at a time, so I don't think it's a question of overflowing some buffer by creating too many notes.

**Expected behavior**

1. Enable the notes widget

2. Create note

3. Create more notes

4. The notes I created before are still there, even days or weeks afterwards

**Screenshots**

**Smartphone (please complete the following information):**

- Device: Poco M3

- Android version: Android 10

- AIO Version: 4.5.1

**Additional context**

**Comment by zobnin** [comment]
Can't reproduce on my phones.

Have you enabled cloud synchronization? 
Have you disabled the MIUI power-saving mechanisms for the AIO Launcher?

**Comment by leliamesteban** [comment]
I don't have cloud synchronisation because I'm using the free version.

I'm not aware of any MIUI power-saving mechanisms specific to the AIO
launcher. I can change it if you tell me what to change.

Battery saving mode was activated, however, so I will try to replicate the
issue without battery saving mode on my phone.

Also, I haven't created any new notes and none have disappeared, so it
looks like it only happens when I create new notes.

**Comment by zobnin** [comment]
Notes widget uses unix date as primary field in db. So if you manipulated in some way with date on your device then new note can overwrite old one. So far, this is the only explanation I can think of.
