### ISSUE TITLE
Headers off maximise widget

### ISSUE THREAD

**Issue by Lorestan00** [zobnin/aio#31]
**Is your feature request related to a problem? Please describe.**
With the headers set to off there is no way to maximise the widget. With headers on you can tap the header to expand a single widget

**Describe the solution you'd like**
Perhaps two finger swipe on widget to expand it

**Describe alternatives you've considered**
Swipe left:) 

**Additional context**

**Comment by Lorestan00** [comment]
I've just realised there is a dot that allows you to maximise the widget already!

**Comment by Lorestan00** [comment]
With standard android widgets there is no dot and I can't see a way of expanding widgets. Am I missing something?

**Comment by zobnin** [comment]
The dot is disabled for Android widgets because it can override important interface elements. But you can set right swipe action to minimize/expand widget in the settings.

**Comment by Lorestan00** [comment]
Problem is I'm using widget action which is working very well. When using widget action can the right swipe default for android widgets by to expand them since there is no other to do this

**Comment by zobnin** [comment]
No. Right swipe reserved for other actions

**Comment by Lorestan00** [comment]
When widget action is, selected right swiping on standard android widgets doesn't do anything....

A way to expand the standard android widget when widget action is picked with headers off would be helpful

**Comment by zobnin** [comment]
Swipe action for compact mode working good but some widgets can intercept swipes so launcher swipe will not word. I can't fix this.
