### ISSUE TITLE
Control Panel behavior 

### ISSUE THREAD

**Issue by Lorestan00** [zobnin/aio#32]
**Is your feature request related to a problem? Please describe.**

Change how control panel widgets function. To allow them to mirror quick panel more closely

**Describe the solution you'd like**

When pressing :- 

wifi it turns off rather than WiFi dialog box opening up

Location pushes you into settings rather than just turning off or setting

Same VPN,  mobile hotspot and airplane mode

Ideally pressing these switches just turns off or on the setting like in quick settings 

**Describe alternatives you've considered**

Long pressing switches takes you to their respective settings

**Additional context**

**Comment by zobnin** [comment]
Buttons open the settings, not toggle them because Android doesn't allow it. That is, what you suggest is technically impossible to do.

**Comment by Lorestan00** [comment]
Ah okay that's a shame
