### ISSUE TITLE
Control panel mirror quick settings

### ISSUE THREAD

**Issue by Lorestan00** [zobnin/aio#33]
**Is your feature request related to a problem? Please describe.**

In quick settings you can add additional switches beyond standard switches from apps e.g. shazam

**Describe the solution you'd like**

It would be great if you could add in switches from apps to control panel 

**Describe alternatives you've considered**

**Additional context**

**Comment by zobnin** [comment]
Technically impossible

**Comment by Lorestan00** [comment]
Oh that's a, shame. Do Google and Samsung have special locked down access to adding a apps quick settings?

**Comment by zobnin** [comment]
Yes. Only system can work with quick tiles.
