### ISSUE TITLE
Tasks separate lines

### ISSUE THREAD

**Issue by Lorestan00** [zobnin/aio#35]
![Screenshot_20220827-032101_AIO Launcher](https://user-images.githubusercontent.com/81394097/187029356-65932cc6-e1ae-45a5-a80c-77a1a8232d29.jpg)
**Is your feature request related to a problem? Please describe.**

Tasks which are entered on separate lines appear in the widget as a sentence (see attached) so you can't identify each task. Also just looks messy

**Describe the solution you'd like**

Tasks appear on separate lines 

**Describe alternatives you've considered**

**Additional context**

**Comment by zobnin** [comment]
Launcher purposefully clutches lines together so that the desktop is not cluttered with endless shopping lists. But in the tasks widget settings there is an option that enables displaying only the first line of the task. You can turn it on and use the first line as a task title.

**Comment by Lorestan00** [comment]
You can could have an option to resize the widget and users can maximise the widget to reveal all tasks.

It just looks pretty messy and doesn't make much sense as a usable task app. Lists should appear as lists no?

The first line option, is great but being able to see a shopping list for example line by line would be good. Having to click to open a new task for each item would be abit cumbersome especially since you have the ability to add multiple items in each task already
