### ISSUE TITLE
Tasks tick off actions

### ISSUE THREAD

**Issue by Lorestan00** [zobnin/aio#36]
**Is your feature request related to a problem? Please describe.**

Tasks can't be actioned through the home screen. They are just static. 

**Describe the solution you'd like**

Tasks can be actioned without having to open widget  through tick box (see attached). 

![Screenshot_20220827-131637_AIO Launcher](https://user-images.githubusercontent.com/81394097/187029890-50d852b7-e025-44b2-9f83-3c8644201b2a.jpg)

**Describe alternatives you've considered**

Open to other ways to achieve this. The above seemed the most obvious 

**Additional context**

**Comment by zobnin** [comment]
I don't think this kind of thing belongs on the desktop. They are too easy to click by accident.

**Comment by Lorestan00** [comment]
Or tap or double tap a  line to close the task?

**Comment by Lorestan00** [comment]
I think the tick box is better as long as its sized reasonably it should be fine. The screenshot is from a task app which does exactly this
