### ISSUE TITLE
Single screen mode activating... 

### ISSUE THREAD

**Issue by Lorestan00** [zobnin/aio#37]
**Describe the bug**

https://user-images.githubusercontent.com/81394097/187031313-3ac6f2f3-3b5e-43b4-b810-187aae5cb18b.mp4

**To Reproduce**

I'm not sure why it happens

**Expected behavior**

Sometimes when unlock my Galaxy fold 3 it's in single screen mode without activating it and the option to turn it on and off is no longer available. By rotating to landscape it resets

**Screenshots**

The attached video shows the description above clearly 

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 6]
 - Android version: [e.g. Android 12]
 - AIO Version: [e.g. 4.3.3]

Samsung galaxy fold 3
Android 12
Latest beta. Its happens on the last 6 betas

**Additional context**

**Comment by zobnin** [comment]
I can't see your video and right can't fix this bug because I don't hove any foldable device.

**Comment by zobnin** [comment]
And please remove placeholder text from template when you create new issue

**Comment by zobnin** [comment]
Do you mean to turn the device on when it is unfolded?

**Comment by Lorestan00** [comment]
That's strange the video is playing in github.

Will remove playholder text in the future

Yep when it's unfolded it defaults to single screen but the option to turn it on disappears. It's happened again. Here are soem screenshots. Not the end of the world if it's not obvious fix. Don't worry



![Screenshot_20220827-152606_AIO Launcher](https://user-images.githubusercontent.com/81394097/187034561-24800933-c0f5-459a-bc10-0b367fe711af.jpg)
![Screenshot_20220827-152623_AIO Launcher](https://user-images.githubusercontent.com/81394097/187034566-06e8c5de-3975-49ad-ad8e-ab5193688b1a.jpg)

**Comment by zobnin** [comment]
Please describe how to solve the problem step by step, about this style:

1. I unfold working device, everything is normal, the screen is divided.
2. I turn off the device (turn off the screen)
3. I turn on the screen again and the screen is no longer split.

Also tell me how often this happens. Always or from time to time? If the latter, what can it depend on?

This kind of information is 100 times more useful than screenshots and videos.

**Comment by Lorestan00** [comment]
Okay I'll try and keep a track. It happens out of the blue. I unfold it and it happens but it's not obvious what the last action is

**Comment by zobnin** [comment]
Please try version 4.6.0-beta2

**Comment by Lorestan00** [comment]
Thanks. Seems fixed now. I haven't been able to replicate the issue
