### ISSUE TITLE
Allow setting a screen time limit, similar to traffic limit.

### ISSUE THREAD

**Issue by luleyleo** [zobnin/aio#4]
In the monitor widget, the screen time does not allow setting a limit, thus it can not display any "progress".

I think it would be cool, if one could set a limit. Then the progress bar could start filled completely (like 100% battery) and then drain until the screen time limit is reached (like 0% battery).

**Comment by zobnin** [comment]
Great idea. To be implemented in one of the next versions.

**Comment by zobnin** [comment]
Version 4.3.1-beta6 now has screen time limiting option. Will be available in the stable version soon.

**Comment by luleyleo** [comment]
Awesome, thank you so much! I bought the pro version now :)
