### ISSUE TITLE
App thinks I haven't purchased premium; premium features still work 

### ISSUE THREAD

**Issue by Calelkestifer** [zobnin/aio#41]
**Describe the bug**
I have purchased the "one-time payment" option to get the premium features which all work, but I have the undeleteable button at the bottom that asks me to pay, the purchased status says not purchased, but all my premium features still work. 

**To Reproduce**
1.) Purchase full version
2.) Change Google account username? 

**Expected behavior**
Premium version recognition

**Screenshots**

![Android Widget supprt and fingerprint triggered private mode](https://user-images.githubusercontent.com/116037761/196290196-62945695-2da2-4bf4-87b1-a240cf565b77.png)

![purchase status](https://user-images.githubusercontent.com/116037761/196290236-f9b5d2f4-546b-4931-b925-9d37ada22df6.png)

**Smartphone (please complete the following information):**
 - Device: LG Stylo 4
 - Android version: Android 8.1.0
 - AIO Version: 4.5.4

**Comment by zobnin** [comment]
just email me: zobnin@gmail.com
