### ISSUE TITLE
Like the (new) "widget switcher" script, but for "categories" and without injecting or removing other widgets.

### ISSUE THREAD

**Issue by Madydri** [zobnin/aio#43]
**Is your feature request related to a problem? Please describe.**
Not a bug. It's a suggestion 😉

**Describe the solution you'd like**
We have now vertically organised "widgets" in witch we can put applications, *and* we have "categories" in witch we can place applications.
Ok, the list of applications a category can already be showed by using the horizontal swipe from the left (or from the right depending of settings) : ok. But sometimes I feel as if it does not work smoothly, as for example my phone has a case with a border higher as the screen: the swipe is then often aborted. Or if the desktop is not locked in AIO editor, the swipe has impact on the widget, or making disappear a notification as it is the same gesture.

**Describe alternatives you've considered**
As the script "widget switcher" I would propose a widget with the different categories icons that a user has defined.
The base gore this functionality already exists in the code for the sidebar.
And when you touch one of these category icons, the linked application icons would appear under this "categories widget" (I would suggest to show them *inside* this new "category widget" to not create additional widgets that could mess up with the rest of the composition of the desktop.

**Additional context**
1/ So the left or right swipe to make appear the list of applications in a category would not be necessary anymore and would not interfere with other swipe gestures.
And the (very useful) "category" classification would be more integrated with the widgets and the "vertical" scrolling logic of AIO
2/ the "vertical" architecture of the desktop of AIO would be more consistent, and the sidebar would only be needed if someone wants to see *all* installed apps.

Thanks for the work 👍

**Comment by zobnin** [comment]
While the idea of the widget itself is interesting (it's similar to what I've already planned), I think the problem with opening the app menu is farfetched. The application menu can be opened with the back button, which is available on any phone.

**Comment by Madydri** [comment]
Hmmm, I did just discovered the android back button to adding as a gesture for the application menu : nice !
Thanks 😉
