### ISSUE TITLE
Back button top left in configuration screens

### ISSUE THREAD

**Issue by Madydri** [zobnin/aio#44]
**Is your feature request related to a problem? Please describe.**
Not a bug. UI suggestion.

**Describe the solution you'd like**
Lots of applications have now there own "back" button inside the app, at the top/left position.
To navigate back in the config screens they don't use the native android back button anymore.
I feel this is getting more and more common and recently browsing through the different AIO config screens it looks to me it had become a habit and that I was missing this back button top/left to go back in the confi screen tree.

**Describe alternatives you've considered**
Adding a "back" button inside the AIO config screens, independent of android back button.

**Additional context**
Harmonisation of UI habbits.

**Comment by zobnin** [comment]
The buttons at the top of the screen are a very poor design. Just use the back button.
