### ISSUE TITLE
Other background colour for options in the config screens that are changed or new comparing to previous release 

### ISSUE THREAD

**Issue by Madydri** [zobnin/aio#45]
**Is your feature request related to a problem? Please describe.**
There are lots of updates of AiO and this is a good thing, but sometimes it's unclear to know what has changed or is new

**Describe the solution you'd like**
Some applications that are actively developed are using a different background colour for the options in the config screens that are new or gave changed.
I suppose this can be done with an additional table in the database, that is reset after each release, and flagged as an option is refactored or added.

**Describe alternatives you've considered**
A distinct background colour for new or changed options (compared to the previous release) would help to understand what gas changed and help discover new functionalities

**Additional context**
No.

**Comment by zobnin** [comment]
Good idea
