### ISSUE TITLE
Movements between widget "my apps" and his clone but not reverse ?

### ISSUE THREAD

**Issue by Madydri** [zobnin/aio#46]
**Is your feature request related to a problem? Please describe.**
We have the "my apps" widget.
This cane be "copied"/"cloned" to create a second kind of "my apps" widget.
Apps/Icons can be moved from the original "my apps" widget to his clones / copies / sons / daughter widgets.
But it is not possible to do the reverse : living an app / icon from a secondary "my apps" widget to the original father/mother "my apps" widget.
More : il the original father / mother "my apps" widget is empty, and we ask to remove it, then suddenly the interface says this will also remove the other "my apps" widgets 😱

**Describe the solution you'd like**
1/ possibly to move back from a child "my apps" widget to the original "my app" widget
2/ ? Make the newly created Cline "my apps" widgets independent from their original source widget ?

**Describe alternatives you've considered**
Null

**Additional context**
The possibility to create multiple instances of a type of widget seems very useful to organise the desktop.
But the (hidden/unexpected) dependency of these cloned instances from there original widget is confusing and can do lose some design work done on the desktop

Thanks for the work 🙏

**Comment by Madydri** [comment]
![IMG_20221103_095756.jpg](https://user-images.githubusercontent.com/70443803/199684497-fc56e167-7a74-4d9c-a684-e84353d85820.jpg)
![IMG_20221103_095831.jpg](https://user-images.githubusercontent.com/70443803/199684520-8b8c7aea-0189-4ef5-8c6e-0ad32a830e7d.jpg)
![IMG_20221103_095936.jpg](https://user-images.githubusercontent.com/70443803/199684609-07404b5a-6b67-4b99-b719-7cae4537b8f4.jpg)

**Comment by zobnin** [comment]
1. There should be no problem moving the applications back. Make sure you don't mix anything up.
2. Historical reasons. The head widget My apps is like the parent of all the other widgets.
