### ISSUE TITLE
Categories appear in App Folders widget

### ISSUE THREAD

**Issue by Lorestan00** [zobnin/aio#47]
**Is your feature request related to a problem? Please describe.**
I've categorised my apps but there doesn't appear to be a way to add the category of apps to thr home screen. It woudl be useful to easily access all categories. 

**Describe the solution you'd like**
Perhaps categories could be added to the App Folders widget. That seems the natural home as categories are groups of apps and appearing in folders would make sense.

**Comment by zobnin** [comment]
Yes. You are right. Next function for App Folders widget will be "Categories as folders"

**Comment by Lorestan00** [comment]
Terrific. Look forward for the next update

**Comment by zobnin** [comment]
Apps Folders widget supports categories in the version 4.6.0-beta7

**Comment by Lorestan00** [comment]
Thanks. Works great.

Just two things - you can't create manual folders if you select categories. It's one or the other. Would be good to do both. For example I would like to create a folder of frequently accessed apps some of these do appear in one of my category folders such as Instagram which is also in the social media category

Linked to this rather than all categories appearing in app folder it would be helpful to be able to select which ones appear. While you can remove a category from App Folder at the moment it also removes it from the App menu as well. App menu is a great way to maintain a drawer of all apps categorised but App Folder it woudl be helpful if it was more bespoke only categories and folders you want

**Comment by zobnin** [comment]
I really don't like what you are suggesting, as it is too complicated a concept that will just confuse users. I'm committed to the KISS principle: Keep It Simple, Stupid

**Comment by Lorestan00** [comment]
It just allows flexibility to both create folders and also use categories as folders. Not that complicated really. You're forcing people to choose with one or the other

**Comment by zobnin** [comment]
Yes, that's right. Because categories and folders are different entities. You would agree that it would be strange if a clothing store had all the shoes and jackets piled together in one place instead of on different counters.

**Comment by zobnin** [comment]
What you are suggesting is mixing. And mixing entities is always a bad idea. The way it works now (swipe to the right and click on the display icon) is separation, as it should be in a clothing store. Now my opinion is this, I don't intend to argue.
