### ISSUE TITLE
App Folder editing

### ISSUE THREAD

**Issue by Lorestan00** [zobnin/aio#48]
**Is your feature request related to a problem? Please describe.**
It's abit cumbersome to drag each app into App folder

**Describe the solution you'd like**
A quicker way to edit might be to have a new folder button. You click new folder and then an app list appears where you can tick apps you want to appear in the folder. To edit ay any time you long press folder to go into edit mode

**Comment by zobnin** [comment]
Yes. Something like this is planned

**Comment by Lorestan00** [comment]
Terrific
