### ISSUE TITLE
App Folder Icon

### ISSUE THREAD

**Issue by Lorestan00** [zobnin/aio#49]
**Is your feature request related to a problem? Please describe.**
App Folders show 4 small app icons which can appear hard to immediately distinguish between each app folder. 

**Describe the solution you'd like**
Beign able to customise the folder so you can change it to a single icon to represent the folder e.g. game controller icon for games folder would make each app folder very clear. Icon pack support would be great

**Comment by zobnin** [comment]
The Apps Folders widget in beta 4.6.0-beta8 now allows you to assign arbitrary icons to folders. And in the case of category mode, these icons will be assigned automatically (changeable).

**Comment by Lorestan00** [comment]
Brilliant.  Thanks

**Comment by Lorestan00** [comment]
Any chance of icon pack support?

**Comment by zobnin** [comment]
Not planned for now

**Comment by Lorestan00** [comment]
Okay
