### ISSUE TITLE
Extracted colors from wallpaper often have poor contrast

### ISSUE THREAD

**Issue by trev-dev** [zobnin/aio#5]
I really like the "extracted wallpaper" colors feature. The only issue I have with it is if the background is on the darker side, the extraction chooses the a pretty dark hex based on the majority of the background color.

This makes the extracted color a pretty poor contrasting color all of the darker themes...which are the majority of the themes. You can barely see the progress bars/timer buttons as a result. Even in lighter backgrounds the derived color is pretty dark.

It would be nice if the color that gets extracted is compared to the "background overlay" for contrast, then adjusted before its applied.

![Screenshot_20220207-220246](https://user-images.githubusercontent.com/28788713/152927853-21cbfffb-3e10-40b7-ba96-5cddb333e953.png)

![Screenshot_20220207-220858](https://user-images.githubusercontent.com/28788713/152928660-bd98c210-68d5-4a0c-ab02-8f1003fd60b7.png)

![Screenshot_20220207-221406](https://user-images.githubusercontent.com/28788713/152929095-d12633a9-2852-4b90-8fba-22b487889792.png)

**Comment by zobnin** [comment]
This is because the color selection algorithm intentionally corrects colors so that they are well suited for displaying white text over them (switch the theme to Flat and you'll see why). And yes, it might be worth responding to display it more correctly in Neon-type styles.

**Comment by trev-dev** [comment]
I customized the theme to use the classic progress bars and it does help a bit.

![Screenshot_20220208-095842-996.png](https://user-images.githubusercontent.com/28788713/153047891-ecef6cd7-52b2-4d96-8407-7e1454b61aee.png)

**Comment by trev-dev** [comment]
It's a huge improvement

![Screenshot_20220217-225144-882.png](https://user-images.githubusercontent.com/28788713/154632767-1b49d9bf-8747-4750-901d-b2573c8e7f99.png)

![Screenshot_20220217-224820~2.png](https://user-images.githubusercontent.com/28788713/154632781-fbb1b9c1-edc4-44e9-804e-3dbd90ac807c.png)

**Comment by trev-dev** [comment]
Even the backgrounds that are super bright are not creating colors that wash out the text/theme.

Great work 👏

![Screenshot_20220217-225714-023.png](https://user-images.githubusercontent.com/28788713/154633593-66e589e8-5c2f-409f-be3c-4c0a6c94b8f7.png)
