### ISSUE TITLE
App Folders changing icon crash

### ISSUE THREAD

**Issue by Lorestan00** [zobnin/aio#50]
**Describe the bug**
When changing icon for app folder the app crashss.

**To Reproduce**
 to reproduce the behavior:
Long press on app folder
Click change icon 
Pick icon
And then the app crashes 

**Smartphone 
 - Device: Samsung galaxy fold 4
 - Android version: 13
 - AIO Version: 4.6.0 beta 8

.

**Comment by zobnin** [comment]
I don't see this problem on the Pixel 4a (Android 13). I also don't see any error reports from your phone. Is error reporting enabled in your AIO settings?

**Comment by zobnin** [comment]
Figured it out. The problem is a modified database schema. The application was supposed to delete the old database after update, but for some reason it didn't. You will have to either reset the application settings, or make a backup, then delete the `appfolders.db` file and restore that backup.

**Comment by Lorestan00** [comment]
Reset settings and then restored backup but still same outcome. Still crashes

**Comment by zobnin** [comment]
You need to delete the appfolders file.db from the backup archive.

**Comment by Lorestan00** [comment]
The restore now doesn't restore the backup. App folder issue isn't happening. Guess I'll have to start scratch and revukdl my setup

**Comment by Lorestan00** [comment]
Okay
