### ISSUE TITLE
App Folders category colours

### ISSUE THREAD

**Issue by Lorestan00** [zobnin/aio#52]
**Is your feature request related to a problem? Please describe.**
The colour picked in categories does not come through app folders. I might be doing soemthugn wrong here perhaps I've nto selected an option but they appear white on black in app folders

**Describe the solution you'd like**
The colour for the category carrying through to app folders. Perhaps an option to shwo colour or keep it white on black

**Comment by zobnin** [comment]
You are using black and white theme :)

**Comment by Lorestan00** [comment]
That makes sense ☺ cheers
