### ISSUE TITLE
Frequent apps - buttons/icon overlap

### ISSUE THREAD

**Issue by Lorestan00** [zobnin/aio#53]
**Describe the bug**
 On the galaxy fold when you open to the main screen buttons/icons overlap on top of another. This is with truncated names on or off. I've tried with both buttons or icons. It's only with split screen on

It's more obvious on buttons.  No issue on main screen 

**To Reproduce**
Open main screen and buttons icons are overlapped

**Screenshots**
![Screenshot_20221227_171144_AIO Launcher.jpg](https://user-images.githubusercontent.com/81394097/209699997-3409514f-021a-478d-ae63-d09fc18ee844.jpg)

![Screenshot_20221227_170925_AIO Launcher.jpg](https://user-images.githubusercontent.com/81394097/209700014-9ec704af-3081-4129-b6d6-ca35aa03c61c.jpg)

**Smartphone (please complete the following information):**
 - Device: galaxy fold 4
 - Android version: 13
 - AIO Version: 4.6 beta 15

**Comment by zobnin** [comment]
How often does this happen?

**Comment by Lorestan00** [comment]
1.It happens every time you go from the cover screen being on to unfolding to the main screen.

2. Only the frequent widget

**Comment by zobnin** [comment]
Did it start after the update or has it always been there?

**Comment by Lorestan00** [comment]
1.It happens every time you go from the cover screen being on to unfolding to the main screen.

2. Only the frequent widget its been there for a while. I can't pinpoint when it started but at least a month. Probably longer

**Comment by zobnin** [comment]
Please write to me: zobnin@gmail.com
