### ISSUE TITLE
Restoring Shortcuts bug

### ISSUE THREAD

**Issue by Lorestan00** [zobnin/aio#54]
**Describe the bug**
I restored a backup and while the my apps widget which had shortcuts appeared to restore when you click any shortcut (see screenshot) I get a 'can't open' message 

**To Reproduce**
1. Click shortcut

**Screenshots**
![Screenshot_20221230_120836_AIO Launcher.jpg](https://user-images.githubusercontent.com/81394097/210069020-f3e2e730-aa02-493b-8ef0-0221e6d0d2c1.jpg)

**Smartphone (please complete the following information):**
 - Device: galaxy fold 4
 - Android version: 13
 - AIO Version: 4.6 beta 18

.

**Comment by zobnin** [comment]
This is normal. When you add shortcuts, they are "pinned" to the application. When you delete an application or clear its settings, the shortcuts are "unpinned" and therefore no longer work.

**Comment by Lorestan00** [comment]
Okay
