### ISSUE TITLE
Extending - Show Icons instead of buttons - option

### ISSUE THREAD

**Issue by Lorestan00** [zobnin/aio#55]
**Is your feature request related to a problem? Please describe.**
It can be tough to tell apart app icons especially if you have lots of apps installed. Many icons can seem similar and if you use the app infrequently it's even less obvious. In app folders when using categories this is particularly evident. 

**Describe the solution you'd like**
The 'Show Icons instead of buttons' option which already exists in frequent apps widget among others is great for being able to switch on buttons so you can read the names of the apps. It would be great if this option could be extended to the app folder widget.

**Comment by zobnin** [comment]
I'm waiting for someone to make the concept of a folder widget without icons, which would not look ugly and would be convenient.

PS In fact, those who prefer buttons have had an option for a long time: this is a frequent apps widget, because it can be swiped to switch between categories :)

**Comment by Lorestan00** [comment]
Oh I know it's, in frequent widgets and others but felt it was most useful in app folders when categories are selected since each category might easily have over a dozen apps. Hard to implement?

**Comment by zobnin** [comment]
I have already said why this has not been done.
