### ISSUE TITLE
Android widget size - folded

### ISSUE THREAD

**Issue by Lorestan00** [zobnin/aio#56]
**Is your feature request related to a problem? Please describe.**
I might be doing something wrong but with regular android widgets you can set the unfolded size but is there a way to set the folded size? At the moment the default is really small e.g. List apps. 

While you can set the unfolded size and keep the widget unfolded all the time being able to switch between two sizes of widget folded and unfolded would be very useful. 

**Describe the solution you'd like**
Essentially a mirror of the unfolded setting but for folded widgets

**Comment by zobnin** [comment]
In folded mode, widgets display a single row. That is why the mode is called "folded". Making it possible to select a number of lines of the folded mode is unnecessarily complicated, which does not give much benefit, but confuses users.
