### ISSUE TITLE
Double tap not working anymore since latest version 4.6.0

### ISSUE THREAD

**Issue by UVERtainment** [zobnin/aio#57]
The double tap to close screen is not working. i've changed to other actions but it is not triggering the action.
have tried restarting the launcher as well as my phone.

**Comment by zobnin** [comment]
Double tap not working anymore on any apps widgets.

**Comment by UVERtainment** [comment]
oh, then where will it work? as the whole screen is full of widgets

**Comment by zobnin** [comment]
Nowhere, double tap will be removed soon
