### ISSUE TITLE
Add app shortcuts to AIO

### ISSUE THREAD

**Issue by dgmltn** [zobnin/aio#58]
I'd like to be able to do this:

![Screenshot_20230114_110137_Chrome](https://user-images.githubusercontent.com/698270/212491743-6c02aad4-b1b7-47a6-b977-930360ee7934.jpg)

Similarly, I'd also like to be able to add app shortcuts (that appear when long clicking an app icon) to an aio app drawer.

**Comment by zobnin** [comment]
You CAN do this.
