### ISSUE TITLE
Alternative ways to launch the Side Menu / Scripts

### ISSUE THREAD

**Issue by dextersgenius** [zobnin/aio#59]
**Is your feature request related to a problem? Please describe.**
On devices without a navbar (where system gesture navigation enabled), its not possible to launch the side menu, because that gesture is registered to the system as the system back action. And because the side menu is inaccessible, we cannot access any scripts.
 
**Describe the solution you'd like**
1. Add other means to launch the side menu, maybe make it available as an action under "Actions", so we can assign a custom gesture. Or make it accessible from the Search icon, as a gesture or in the Quick Apps menu.
2. Show scipts in other parts of the launcher. Eg allow us to add a script directly to an empty widget, or allow us to add a script to the Quick Apps Menu.

**Describe alternatives you've considered**

**Additional context**

**Comment by zobnin** [comment]
You can open menu not only by back button, but also with back gesture. Also you can assign it to any other gesture in the "Actions" section. Scripts can be added via settings also.

**Comment by dextersgenius** [comment]
There is no "side menu" option in Actions or Back Gesture, nor is there an option to add scripts to a widget. Please reopen this ticket.

**Comment by zobnin** [comment]
1. Back gesture causes the same action as the back button (if this is not the case on your phone - ask the phone manufacturer).
2. Side menu option is named "Applications menu".
3. Scripts can be added to the screen via AIO Settings -> Scripts section.

Please study the app before creating tickets and distracting people.

**Comment by dextersgenius** [comment]
> 1. Back gesture causes the same action as the back button (if this is not the case on your phone - ask the phone manufacturer).
> 
>     2. Side menu option is named "Applications menu".
> 
>     3. Scripts can be added to the screen via AIO Settings -> Scripts section.
> 
> 
> Please study the app before creating tickets and distracting people.

You should fix the language string in the app and Gitbub, because you're calling it "side menu" in some places and "Applications menu" in other places, which is confusing.

Regardless, the scripts do not appear in the "Applications menu" even though I've ticked the box which says "show almost scripts in the side menu".

**Comment by zobnin** [comment]
Once again: study the application.
