### ISSUE TITLE
Color of screen time monitor widget not correct

### ISSUE THREAD

**Issue by JulienBest** [zobnin/aio#60]
Using the monitor widget it shows things like battery status, screen time etc. as dots.
The dot color changes to red if the battery is below a certain percentage or, in case of the screen time, if it's above the specified screen time limit.
At midnight, the screen time resets but the red color remains until the manual restart of the app.

**Comment by zobnin** [comment]
What AIO version?

**Comment by JulienBest** [comment]
> What AIO version?

4.6.2

**Comment by zobnin** [comment]
Will be fixed in the next version. Thank you!
