### ISSUE TITLE
Auto update to 4.6.2 caused task list to be cleared out.

### ISSUE THREAD

**Issue by coderMaff** [zobnin/aio#61]
**Describe the bug**
When returning to the phone after the 4.6.2 update I noticed my tasks list box which had several complete tasks in it before the update was now empty.

**Expected behavior**
Completed tasks remain after version updates.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7
 - Android version: 13
 - AIO Version: 4.6.2

**Comment by zobnin** [comment]
Completed tasks are automatically deleted after one day. You can change this behavior in the settings.
