### ISSUE TITLE
Widgets white after turning on the phone

### ISSUE THREAD

**Issue by JulienBest** [zobnin/aio#62]
Turning on the phone after it was turned off, the widgets are white with light gray text. After restarting the AIO Launcher (version 4.6.2), it works again.

![Screenshot_20230209_124943_ru execbit aiolauncher_edit_8489092804432](https://user-images.githubusercontent.com/36485656/217845128-a160c586-d877-44f3-8e88-d4ae489a2704.jpg)

**Comment by JulienBest** [comment]
> What phone and Android version?

Android 10
Huawei P30 Pro (VOG-L29)

**Comment by zobnin** [comment]
Can you try it on the other phones? I can't repeat this bug on my phones.

**Comment by JulienBest** [comment]
> Can you try it on the other phones? I can't repeat this bug on my phones.

Hmm I don't have multiple phones. It's not a big problem, I just restart the launcher after the phone boot but I thought maybe it's a common bug and I'll report it to help. Thanks for checking :)

**Comment by zobnin** [comment]
Should be fixed now
