### ISSUE TITLE
can't add a note from share

### ISSUE THREAD

**Issue by nathgit** [zobnin/aio#63]
I tried to add a note through the share feature from another app. It took me back to the home screen, but didn't add the note.

**To Reproduce**
1. open any app
2. type some text
3.  share text (AIO Launcher > Add note)
4. get kicked back to home screen, but see note hasn't been added

Apps I tried:
my browser (duckduckgo) - didn't work
YouTube - didn't work
Gmail - didn't work
clipto (clipboard app) - worked, but note was deleted when I tried to add a note from duckduckgo again (which again didn't get added either.) All 4 apps are set to optimize battery use, but since it worked with clip to I wouldn't think that could be the problem.

**Expected behavior**
1. open any app
2. type some text
3.  share text (AIO Launcher > Add note)
4. get sent to home screen & back to app.
5. close app & see note.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Moto g play 2021
 - Android version: android 11
 - AIO Version: [e.g. 4.3.3]

**Additional context**

**Comment by zobnin** [comment]
What app version? Don't see this problem on my phones.

**Comment by nathgit** [comment]
Do you mean AIO? 4.6.2
