### ISSUE TITLE
Steps in Monitor

### ISSUE THREAD

**Issue by leojcal** [zobnin/aio#64]
**Is your feature request related to a problem? Please describe.**
Would be great to see how many steps I've taken at a glance by showing them in the monitor.

**Describe the solution you'd like**
I know the monitor is more meant to be a phone monitor, but I think a lot of us track steps, and this would be a really clean way to show them using existing features. 

**Describe alternatives you've considered**
I currently use the google fit widget, but it's big, so I keep it at the bottom of my screen and have to scroll to it. A lot of 3d party apps tracking steps are questionable security-wise. 

**Additional context**
Best launcher by far. Been using a month now and very happy. Thanks dev(s)!

**Comment by zobnin** [comment]
There will be the Health widget in the next version (already available in the beta version). It is a compact one line widget with various info like steps, distance and heart rate.

**Comment by leojcal** [comment]
Wow, sounds great!
