### ISSUE TITLE
App icons in search results

### ISSUE THREAD

**Issue by leojcal** [zobnin/aio#65]
**Is your feature request related to a problem? Please describe.**
Whenever I search for an app, it can be hard to find in the results as they look like every other result. 

**Describe the solution you'd like**
Being able to see apps as icons in search results. This would not only make apps easier to locate, but other results would stand out more as well as we would know immediately they aren't apps. Obviously this should be a choice left to the user. 

**Describe alternatives you've considered**
I already turned off web search results, as it was too conflicting with opening apps. I also auto- display the alphabet in the app drawer, which is also a fast way to find apps.

**Comment by zobnin** [comment]
Planned for the next version

**Comment by leojcal** [comment]
Amazing! Sorry if these issues were posted before. Great work and thank you!
