### ISSUE TITLE
Theme b/w by system 

### ISSUE THREAD

**Issue by rokdd** [zobnin/aio#66]
**Is your feature request related to a problem? Please describe.**
The screen is very bright at night using the the cards theme. Even I am using the phone in dark rooms and would be nice to change colours by system settings for black and white.

**Describe the solution you'd like**
A option for mapping b+w to the wanted theme  or a special theme to respect the colours of the system

**Comment by zobnin** [comment]
Just use material you or material Mono theme

**Comment by rokdd** [comment]
I use material you now and still I see no labels for example because white in front of white has not such a good contrast

**Comment by zobnin** [comment]
That's not what it should look like. What version of Android and your phone?

**Comment by rokdd** [comment]
Version 11

**Comment by zobnin** [comment]
What phone?

**Comment by rokdd** [comment]
Fairphone

**Comment by rokdd** [comment]
Well great reaction for somebody who paid for your app. Goodbye.

**Comment by zobnin** [comment]
This is a normal reaction. When you created the issue you were offered a template in which you should have specified your phone and OS version, which would have helped me to solve your problem faster. You simply erased those fields. Then I asked you two questions: about the Android version and about your phone, you ignored the second question, when I asked it again you didn't even bother to specify your phone model. I understand that you might be lazy to answer my questions in detail, but this in turn means that you don't really want your problem to be solved. And if you don't want that, then I won't waste any more of my time.
