### ISSUE TITLE
Email widget Gmail button doesn't work

### ISSUE THREAD

**Issue by Ludonope** [zobnin/aio#67]
**Describe the bug**
On the email widget when I try to login and click on Gmail, nothing happens. The other options do work though.

I'm not sure but I think the very first time it worked but I cancelled the Gmail login at the time as I was just starting to setup. Take that info with a grain of salt tho.

**To Reproduce**
1. Go to the email widget
2. Click "tap to login"
3. Click on "Gmail"

**Expected behavior**
A menu or popup to login with Google should open up I guess.

**Smartphone (please complete the following information):**
 - Device: OnePlus 9 Pro
 - Android version: Android 11
 - AIO Version: 4.7.2

**Additional context**
I tried to reset the login of the email widget and restart my phone.

**Comment by zobnin** [comment]
Authentication using your Google account will not work if you do not have gapps installed or the AIO Launcher is not downloaded from official sources. Use an IMAP connection.
