### ISSUE TITLE
Home Assistant integration?

### ISSUE THREAD

**Issue by p6002** [zobnin/aio#68]
Have you thought about adding some integration with Home Assistant so that you can display entities and control them with the AIO launcher?

Technically this is probably possible and quite "clean" to implement. What are your thoughts on this? 

https://developers.home-assistant.io/docs/api/rest/

**Comment by zobnin** [comment]
Can you give me an example of when it would be convenient?

**Comment by zobnin** [comment]
Didn't get a response. Closing issue.
