### ISSUE TITLE
Can't access Android data folder anymore for map files

### ISSUE THREAD

**Issue by CaptainFrosty** [zobnin/aio#69]
**Describe the bug**
Data folder for AIO Launcher is now inaccessible

**To Reproduce**
1. Try to access folder in any file manager
2. No access

**Expected behavior**
The files already there still work but I can't change them

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S22+
 - Android version: Android 13/OneUI 5.1
 - AIO Version: 4.7.4-beta7

**Comment by zobnin** [comment]
Maps widget still has experimental status so it will be fixed later.

**Comment by stylpe** [comment]
There's another consequence of this, which is that I don't have a way to make any custom scripts.

**Comment by stylpe** [comment]
Found a workaround right away: the new AIO store app lets me add local files as scripts too 😁
