### ISSUE TITLE
Even if "automatic folding" in un-ticked, the widget get folded.


### ISSUE THREAD

**Issue by Madydri** [zobnin/aio#7]
![IMG_20220217_231038.jpg](https://user-images.githubusercontent.com/70443803/154579474-86bedde4-e46f-4e63-96d8-e579f65b96ff.jpg)
- ![IMG_20220217_231107.jpg](https://user-images.githubusercontent.com/70443803/154579532-2a4c2bdb-66f1-41c8-9424-0b5bac1780df.jpg)
![IMG_20220217_231126.jpg](https://user-images.githubusercontent.com/70443803/154579578-a6ad7061-06ac-4676-a84b-7a89b2e32890.jpg)
![IMG_20220217_231327.jpg](https://user-images.githubusercontent.com/70443803/154579716-92d416dc-b628-484d-bba9-840bc0e16fdd.jpg)

**Comment by zobnin** [comment]
By its nature folding itself is an option and not state. It means that you can fold/unfold even empty widget.
