### ISSUE TITLE
Material Theme Colors Bugged

### ISSUE THREAD

**Issue by TragicNet** [zobnin/aio#70]
**Describe the bug**
The Material themes have dark background and black text for widgets. And the color palette is not applied properly.

**Expected behavior**
Fix color values. Use colors from the palette and or provide an option to select colors from the palette. Can also allow users to set transparency of widgets.

**Screenshots**
![Screenshot_2023-06-08-14-02-08-626_ru.execbit.aiolauncher.jpg](https://github.com/zobnin/aio/assets/67355216/537d82fb-046e-4e0a-a318-32d043d2f80f)

![Screenshot_2023-06-08-14-15-10-444_ru.execbit.aiolauncher.jpg](https://github.com/zobnin/aio/assets/67355216/976b532e-6066-4acb-b61c-a39adc2cba49)

**Smartphone:**
 - Device: Redmi 6 Pro
 - Android version: 9
 - AIO Version: 4.7.5

**Additional context**
Some versions back, the Neon theme used to provide accurate dynamic colors.

**Comment by zobnin** [comment]
Duplicate #62
