### ISSUE TITLE
CATEGORIES Widget resets the selected category when unfolding the widget.

### ISSUE THREAD

**Issue by mjdjohansson** [zobnin/aio#72]
**Describe the bug**
CATEGORIES Widget resets the selected category to the first category in the list, when the widget is unfolded.

**To Reproduce**
1. Settings > WIDGET SETTINGS > App folders > Show categories instead of folders [ON].
2. Trigger the "Unfold all widgets" action OR the "Swipe right action: Folded mode", OR click on the widget header to unfold.

**Expected behavior**
The CATEGORIES Widget should always remember and keep the last used category selected, even when the widget is folded and unfolded again.

**Smartphone**
 - Device: Google Pixel 7
 - Android version: 13
 - AIO Version: 4.8.1 (901501)

**Comment by zobnin** [comment]
Will be fixed in the next version

**Comment by mjdjohansson** [comment]
The issue still persists in version 4.9.0-beta40.

**Comment by zobnin** [comment]
Yes. It is partially fixed now. Will be fixed later.
