### ISSUE TITLE
Split the "Frequent apps" widget into 3 new separate widgets: Last-launch-time / Launch-count / Time-of-use.

### ISSUE THREAD

**Issue by mjdjohansson** [zobnin/aio#73]
**Is your feature request related to a problem? Please describe.**
I would like to have a widget showing "my last used apps" AND another widget showing "my frequently used apps" at the SAME time. 

**Describe the solution you'd like**
Split the "Frequent apps" widget into 3 new seperat widgets, each with a different sorting method: Last-launch-time / Launch-count / Time-of-use.

**Describe alternatives you've considered**
Maybe something similar to the way you can create additional widgets inside the "My apps" widget settings and add them to a "Widget list"?

**Comment by zobnin** [comment]
It seems to me that this is too narrow a task (it's really hard for me to imagine under what circumstances it might be needed) to complicate the widget so much.

**Comment by mjdjohansson** [comment]
Yes, this might be a somewhat narrow task, but I still think it would be a very useful addition. 

If you ignore the option to sort "By time of use", you could replace the normal "Frequent apps" widget with 2 new versions of the widget, each with it's own predefined sorting method. This way you could add both versions of the widget to the home screen and use them simultaneously (screenshot). 

Why? This would give you perfect access to the last apps you used and also the apps you are most likely to use next. Kind of a compact personalized app drawer on your home screen. If you need to see any of the apps in between, you can still use the sortable Side menu or Search. 

If you only have access to a widget showing your frequently used apps, you will have to keep on using Search every time you want to open newly installed or rarely used apps. Even if they were the last apps used. On the others hand, if you only have access to your last used apps, you will most likely have to use Search to find your frequently used apps instead. So the 2 different widgets would really complement each other.

For a non developer, this feels like it could be done with some copy widget, paste widget plus some changes, but I know that in reality it must be a lot more complicated than that.

So, if you still think this idea is not worth pursuing, I will not go on about it anymore.

Anyways, thank you for this great launcher and your hard work.

![Screenshot_20230813-002223.png](https://github.com/zobnin/aio/assets/121413314/796b3767-3a66-4551-bc2d-d715334f3f63)

**Comment by zobnin** [comment]
If you omit the phrase "you have to use search", everything falls into place. The fact is that the search is just a supplement to frequently used applications. The frequently used widget shows you what you use most often, and search shows you what you launched last time. And these lists don't overlap, because what you run all the time ends up in the frequently used widget and you start using it instead of search. In my opinion this approach is much more intuitive.

**Comment by mjdjohansson** [comment]
Thank you for the clarification. Yes, that makes perfectly sense. I somehow wrongly assumed that Last Apps and Latest Searches referred to the same app list. Maybe that lead to some confusion.

So if I change my original feature request to:

Could you implement a widget with shortcuts to the last apps that I searched for?

Is that a feature you would consider worth adding?

**Comment by zobnin** [comment]
As I said I don't see the point of this as the recent searches widget is already in the search box.

**Comment by mjdjohansson** [comment]
I guess for the same reasons we use all the other redundant widgets. Efficiency and flexibility, just to name two.
