### ISSUE TITLE
False alignment of icons in Latest Searches list in Right-handed mode.

### ISSUE THREAD

**Issue by mjdjohansson** [zobnin/aio#75]
When the Right-handed mode is activated, the app icons in the Latest Searches list are aligned to the left instead of to the right (screenshots).

![Screenshot_20230815-022339.png](https://github.com/zobnin/aio/assets/121413314/8bfd07d0-ad4d-4d1b-9f7f-e8d52c5aee5f)

![Screenshot_20230815-022223.png](https://github.com/zobnin/aio/assets/121413314/97170ec9-7a29-4c79-8c5f-e516317b32d3)

![Screenshot_20230815-021939.png](https://github.com/zobnin/aio/assets/121413314/cdea9c4f-a74f-4438-885d-a8da1539ab93)

**Comment by zobnin** [comment]
Thank you. Will be fixed asap.

**Comment by mjdjohansson** [comment]
That was fast. I see you already fixed the alignment issue.

I couldn't help but notice, that the latest search is added to the left of the previous search results, instead of to the right. That doesn't seem right to me. Wouldn't it feel more natural if the latest search always appeared above the magnifying glass.

![Screenshot_20230816-030828.png](https://github.com/zobnin/aio/assets/121413314/84ca4b65-3f01-4e5a-b0a4-6018f55e917a)

![Screenshot_20230816-030800.png](https://github.com/zobnin/aio/assets/121413314/62436765-6a49-4cb6-a43a-2792a1a9d2cf)

![Screenshot_20230816-030740.png](https://github.com/zobnin/aio/assets/121413314/68accf9c-a829-410d-8c55-f1020972350e)

![Screenshot_20230816-032357.png](https://github.com/zobnin/aio/assets/121413314/2dd4149d-6584-46c8-9a38-043ce4cb6f72)
