### ISSUE TITLE
Alternatives to color coding of Actions in the Search Window?

### ISSUE THREAD

**Issue by mj-sson** [zobnin/aio#76]
Is there another way to show which App an Action in the Search Window belongs to? Color coding alone doesn't really work in situations like this (screenshot).

![Screenshot_20230815-142947.png](https://github.com/zobnin/aio/assets/121413314/1922d94e-10c1-4368-a9d2-3c75567460c4)

**Comment by zobnin** [comment]
I don't know how to solve this problem yet

**Comment by mjdjohansson** [comment]
I thought, since the Actions list is folded by default, maybe unfolding that list could group the related actions together and list them under their respective app names?

ACTIONS "APP NAME" 
                                        001 002 003 004
ACTIONS "APP NAME" 
                                                005 006 007                                     ACTIONS "APP NAME" 
                                        009 010 011 012 

But maybe that's only possible with some apps and their actions?

![Screenshot_20230820-005546.png](https://github.com/zobnin/aio/assets/121413314/ddbb8a02-8155-4031-bc02-1abc79b5c4aa)

**Comment by zobnin** [comment]
It is working when you type exact app name and see only one result.

**Comment by mjdjohansson** [comment]
Yes, but not the other way around. 

But then again, if you already know the name of the action, you probably also know what app name to type to find that action. So with that workaround in mind, I guess this is more of an esthetical than a practical problem. 

Except maybe when you have identically named actions in the latest searches? Which admittedly is a kind of specific scenario.

![Screenshot_20230825-151257.png](https://github.com/zobnin/aio/assets/121413314/c5839d86-b6d2-47c2-9009-13183e03a47b)

**Comment by zobnin** [comment]
Again I don't have an immediate solution to this problem. I have to think about it.

**Comment by mjdjohansson** [comment]
Sorry, I didn't mean to sound pushy. I was just trying to help.

**Comment by mj-sson** [comment]
Solved in 5.4.1-beta5 (903171) 🙂
