### ISSUE TITLE
Access the new Menu Style list One-handed.

### ISSUE THREAD

**Issue by mjdjohansson** [zobnin/aio#77]
I really like how you can pull down the lists inside the Side menu, enabling you to reach the top of the list from the bottom of the screen. Equivalent to the very practical One-handed mode on the home screen. 

It would be great if you could do the same with the newly added Menu Style list at some point.

![Screenshot_20230815-210923.png](https://github.com/zobnin/aio/assets/121413314/7c813243-67af-4d44-91c6-49115de67662)

![Screenshot_20230815-210936.png](https://github.com/zobnin/aio/assets/121413314/f0cbe8e6-e04f-48ea-8c5a-a2457bdd6ff3)

**Comment by zobnin** [comment]
In the next version style menu will be at the bottom
