### ISSUE TITLE
default sms app setting seems to not be respected

### ISSUE THREAD

**Issue by wchristian** [zobnin/aio#79]
**Describe the bug**
i have google messages set as my default sms app, but aio's sms button opens the samsung one

**To Reproduce**
configure google sms app as default in system settings
tap sms button in aio

**Expected behavior**
i expect to see the google sms app open

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S22
 - Android version: 13
 - AIO Version: 4.8.1

**Comment by zobnin** [comment]
It works without problem on all my phones.
I think you just changed SMS app int he Dialer widget settings.

**Comment by wchristian** [comment]
dialer widget settings says standard, system sms setting says google messages

![image](https://github.com/zobnin/aio/assets/175467/e752c883-33ac-4dc0-b4d5-acb63ccca0ac)
![image](https://github.com/zobnin/aio/assets/175467/498ce5d1-ab6d-44c5-878c-572c3c8e22b6)

**Comment by wchristian** [comment]
maybe aio gets confused because the name for both apps is literally just "messages"

**Comment by zobnin** [comment]
This is probably a peculiarity of your firmware, there is no such problem on pure Android. Just select the desired application in the AIO settings and that's it.
