### ISSUE TITLE
Scripts not working 

### ISSUE THREAD

**Issue by eupeuta** [zobnin/aio#8]
The Inspiration and Wikipedia scripts don't work for me. They are just stuck on loading.

**Comment by zobnin** [comment]
What phone?
What Android version?
What app version?
Where are you from?
Are you using a VPN or ad blockers?

Where did you download the app?

**Comment by eupeuta** [comment]
I have a Samsung Galaxy Z Fold 3. Android 12. App version: 4.3.2-beta12 (901355).  I live in the USA. Yes, I am using AdGuard premium with VPN enabled.

I downloaded the app from the Google Play Store.


Best regards,
RN

----------------------------------------

*From: *zobnin ***@***.***>
*To: *zobnin/aio ***@***.***>
*CC: *eupeuta ***@***.***>; Author ***@***.***>
*Date: *Feb 22, 2022 11:22:39 PM
*Subject: *Re: [zobnin/aio] Scripts not working (Issue #8)

**Comment by zobnin** [comment]
Try to disable ad guard

**Comment by eupeuta** [comment]
Thanks! Will do!


Best regards,
RN

----------------------------------------

*From: *zobnin ***@***.***>
*To: *zobnin/aio ***@***.***>
*CC: *eupeuta ***@***.***>; Author ***@***.***>
*Date: *Feb 23, 2022 1:24:02 AM
*Subject: *Re: [zobnin/aio] Scripts not working (Issue #8)

**Comment by eupeuta** [comment]
It worked! Thank you so much! 🙏🏽

I just installed AIO yesterday! And it is amazing! 😊


Best regards,
RN

----------------------------------------

*From: *zobnin ***@***.***>
*To: *zobnin/aio ***@***.***>
*CC: *eupeuta ***@***.***>; Author ***@***.***>
*Date: *Feb 23, 2022 1:24:02 AM
*Subject: *Re: [zobnin/aio] Scripts not working (Issue #8)
