### ISSUE TITLE
Quick Launch feature.

### ISSUE THREAD

**Issue by mjdjohansson** [zobnin/aio#80]
Maybe you could add a feature to the search window, that allows the user to launch the closest matching app in search, when the enter key is pressed?

If no matching app is found, then the internet search could be opened instead.

And if the search field is empty, then the latest search could be launched.

Just an idea, but maybe something in that direction.

**Comment by zobnin** [comment]
I removed this feature for two reasons:

1. Unlike other launchers in AIO the search results appear at the bottom of the screen so there is no problem to click on the application. It's likely that you're just out of habit.

2. It's not uncommon to launch an app in the wrong place. I myself many times faced a situation when I needed to open exactly the Internet search and not the application shown by AIO.

**Comment by mjdjohansson** [comment]
Thank you for explaining why you decided to remove the feature.

I was actually trying out some other launchers with this feature and I somehow got so used to it, that when I came back to AIO, it just felt like it was missing. But I agree with you. Even if it would feel right, it wouldn't really add any benefits to AIO.
