### ISSUE TITLE
Search button gestures in the Search window? 

### ISSUE THREAD

**Issue by mjdjohansson** [zobnin/aio#81]
The Search button on the Home screen allows you to assign diffent actions to different gestures. Wouldn't it make sense if the identical Search button in the Search window would allow you to do the same? 

In my opinion, this would improve consistency and enhance the Search window, without interfering with any existing elements. 

**Example:**

- **Open application on click:**
> Start Internet search (default) / 
> Open default Browser app (if search string is empty).

- **Swipe the Search buttons to the side:**
> Open Applications menu. 

- **Swipe the Search buttons to the up:**
> Open Search window settings.

- **Long pressing the Search button:**
> Clear Search history.

**Comment by mjdjohansson** [comment]
Gestures aren't everybody's cup of tea, I guess :)

Maybe you could make the internal actions accessible to gesture navigation apps instead? 

That way you wouldn't have to deal with confusing gestures, while still letting other users decide if they want to use gestures or not.

**Comment by zobnin** [comment]
Internal actions already available for external apps: https://github.com/zobnin/aiolauncher_scripts/wiki/Tasker-and-ADB-commands

**Comment by mjdjohansson** [comment]
Awesome! I didn't know that. Thank you :) 

I noticed that the link "How to use, click to open instruction" in the Tasker settings doesn't seem to work at the moment. But maybe that's just temporary?

https://aiolauncher.app/api.html

![Screenshot_20230912-141133.png](https://github.com/zobnin/aio/assets/121413314/9c3b6d6e-5cd2-4724-b173-03c5b4b42f5f)

Also, in the GitHub link you posted above, there seems to be an inconsistency in the Tasker screenshot:
 
Under Extra it says "widget:%DEVMAN %DEVMOD" when I think it was meant to be "cmd:apps_menu"?

https://github.com/zobnin/aiolauncher_scripts/wiki/Tasker-and-ADB-commands

![Screenshot_20230913-012923.png](https://github.com/zobnin/aio/assets/121413314/1d166255-24d8-45b5-8634-5f4e67bba8d9)

**Comment by zobnin** [comment]
Thanks for the info. Fixed.
