### ISSUE TITLE
Delete icon or uninstall app?

### ISSUE THREAD

**Issue by mjdjohansson** [zobnin/aio#82]
Long-press icon > Edit > Delete > Do you want to uninstall this app?

I think the Delete label is a bit ambiguous in this situation. To me, Delete also implies removing the icon from the widget rather than actually uninstalling the app itself. 

I would just call it "Uninstall app" instead.

![Screenshot_20230913-163427.png](https://github.com/zobnin/aio/assets/121413314/e09a869d-94a3-4997-b265-40333c9bea5d)

![Screenshot_20230908-135413.png](https://github.com/zobnin/aio/assets/121413314/b812db75-03f5-4361-873c-e7c253805dbe)

![Screenshot_20230908-135424.png](https://github.com/zobnin/aio/assets/121413314/648a70df-9c47-4e9c-b6b1-030dc305de84)

**Comment by zobnin** [comment]
I rename it in the next version. Thanks.
