### ISSUE TITLE
Swipe up gesture actions 

### ISSUE THREAD

**Issue by Rainerr123** [zobnin/aio#83]
Clicking the search button takes more time and is harder than just doing a swipe up gesture like stock android

My aio launcher setup doesn't have enough widgets to scroll, I think there should be swipe up gesture options like there is with pull down or an option to swipe up to open the search.
This would only open it when swiping up from the bottom of your home screen (when the "reached bottom of screen" stretch animation plays)

**Comment by zobnin** [comment]
Will do in the next version

**Comment by mj-sson** [comment]
Gesture added in AIO 5.3.2 😊
