### ISSUE TITLE
Show the day of the week in the calendar widgets?

### ISSUE THREAD

**Issue by mj-sson** [zobnin/aio#84]
Could you maybe add the day of the week to the dates in the calendar widgets? Something like this:

Event - Today: Sun Sep 17 23:00-00:00
Event - Tomorrow: Mon Sep 18 01:00-02:00
Event - Wed Sep 20 22:00-23:00
Event - Fri Sep 22 18:00-19:00

![Screenshot_20230917-204444.png](https://github.com/zobnin/aio/assets/121413314/009bebec-669e-474e-bf44-ef1487cf6168)

**Comment by zobnin** [comment]
Will add option later

**Comment by mj-sson** [comment]
Option added in AIO 5.3.3 😀
