### ISSUE TITLE
Beta changelog?

### ISSUE THREAD

**Issue by mjdjohansson** [zobnin/aio#85]
Would it be possible to have the changelog in the beta (x.x.x-betaxx) versions of the AIO Launcher, also list some changes between the beta releases? The current changelog only shows changes between the official (x.x.x) releases.

I assume the changes between beta releases are subtle, but even so, I believe many beta testers would find it interesting to know what's changed since the last update.

**Comment by mjdjohansson** [comment]
So would you mind explaining to me why you have labeled this invalid?

**Comment by zobnin** [comment]
Write to me in Telegram: @ezobnin
