### ISSUE TITLE
Header of topmost widget disappears?

### ISSUE THREAD

**Issue by mjdjohansson** [zobnin/aio#86]
The topmost widget on the home screen doesn't have a header. This also happens in the one-handed mode, so the header isn't just hidden under the status bar. I first noticed this in the current version, but I have no idea if this is something new or not.

AIO Version: 4.9.0-beta40
Android: 13
Device: Google Pixel 7

![Screenshot_20230923-191648.png](https://github.com/zobnin/aio/assets/121413314/1d29df8a-0afe-4b28-92d4-a232a8c6e221)

![Screenshot_20230923-191633.png](https://github.com/zobnin/aio/assets/121413314/892ade3f-7fdd-48df-a2a5-e7609d69f563)

![Screenshot_20230925-021550.png](https://github.com/zobnin/aio/assets/121413314/2524debb-55dc-4fd6-838c-e3ee453ef3e4)

**Comment by zobnin** [comment]
It's always worked that way. Since the first version. You probably just had a hidden widget at the very top before.

**Comment by mjdjohansson** [comment]
Yes, that probably explains why I didn't notice it before :)

But why hide the topmost header in the first place? I can't really think of a situation where that might be beneficial.

**Comment by zobnin** [comment]
Design

**Comment by mjdjohansson** [comment]
Okay, so purely for esthetic reasons then.
