### ISSUE TITLE
Calendar search results unfolded by default?

### ISSUE THREAD

**Issue by mjdjohansson** [zobnin/aio#89]
When using the calendar search script, the calendar results don't appear folded like the other groups of search results do. Also, the folded symbol shouldn't be seen when the results are already unfolded.

![Screenshot_20231010-020425~2.png](https://github.com/zobnin/aio/assets/121413314/f9237f8a-4388-4f83-9e47-5e3a6fe78009)

After manually folding the results, everything looks fine.

![Screenshot_20231010-020436.png](https://github.com/zobnin/aio/assets/121413314/e83c854a-1480-47a9-bf81-f5485e27d92c)

When continuing the search, the results are unexpectedly unfolded again. This time the folded symbol is hidden correctly.

![Screenshot_20231010-020448~2.png](https://github.com/zobnin/aio/assets/121413314/b085ad23-b5f5-420f-a7df-fc6b677c8b68)

This behavior is only noticeable when the experimental setting: Number of lines in the search history, is changed to more than one. 

![Screenshot_20231010-020730~2.png](https://github.com/zobnin/aio/assets/121413314/3bffb50d-b192-483b-907b-4c5a756d7566)

Since it's an experimental setting, it maybe isn't supposed to work with the calendar script (yet). But the other scripts do work, so I thought I'd report it anyway.

**Comment by zobnin** [comment]
It is a bug. Will be fixed in the next version. Thank you.
