### ISSUE TITLE
White bars in Monitor widget

### ISSUE THREAD

**Issue by JakeEP** [zobnin/aio#9]
Hi, I have the following issue:

![screenshot_aiolauncher](https://user-images.githubusercontent.com/17517802/155295638-ccef93e5-c2a2-4c1a-b0b1-e1cacb809957.jpg)

I've had the issue for at least two months I think, multiple phone restarts since then. I'm on a Huawei. I had previously used the launcher for at least a year, I think, without this bug. I have no other issues with the launcher apart from this one so far.

**Comment by zobnin** [comment]
In the monitor widget, you have white text instead of black. This means that you changed it yourself in the theme settings.

**Comment by JakeEP** [comment]
Okay that more or less fixes it, I don't remember making that change, apologies. Though I'm still not a fan of the bars, which seem to be random sizes (see e.g. the bar sitting at half the size of the "Screen: " statistic) and still exist on default theme settings like Flat.

Thanks
