### ISSUE TITLE
Activate Edit mode by long pressing widget header?

### ISSUE THREAD

**Issue by mjdjohansson** [zobnin/aio#91]
I'm looking for a convenient way to activate the Edit mode without using the Swipe right action, since I'm already using that for the Folded mode. 

The most intuitive solution I can think of would be to simply long press the widget header. This would activate the Edit mode and allow you to edit and move the widget.

Another possible solution could be an 'Edit all Widgets' action that can be triggered with one of the other gestures.

**Comment by zobnin** [comment]
I don't understand what the problem is, as the global edit mode opens via a long hold on the search button.

**Comment by mjdjohansson** [comment]
I'm sorry, I should have been more specific.

It takes two steps to open the Global edit mode (first long holding the search button, then pressing the edit widgets button). I'm looking for a faster alternative that can open the Edit mode in one single step.

**Comment by zobnin** [comment]
It seems to me that opening global edit mode is a rare enough task for which it's fine to use two clicks.

**Comment by mjdjohansson** [comment]
Yes, but I wasn't looking for a faster way to open the GLOBAL Edit mode. I was looking for a new and fast way to open the SINGLE Edit mode in one step.

Normally I would just use the Swipe right action for this, but I need that action to fold and unfold my widgets now. That means I have to use the long way around every time I need to edit a widget, which is a bit annoying when you are used to a more convenient way.

**Comment by mjdjohansson** [comment]
And editing a widget is not a rare task in my opinion. Otherwise I don't understand why you created the Swipe right action > Edit mode, in the first place.

**Comment by zobnin** [comment]
The reason for choosing the widget editing gesture is quite different. I needed a way to show new users that each widget has different display modes and settings. Swiping to the side was a good choice, because many users intuitively swipe sideways because they are used to doing it in other launchers to switch screens.

**Comment by mjdjohansson** [comment]
Thanks for clearing that up. 

So what would you recommend to the more experienced users? To use the Folded mode, Widget action, or Delete? Or would you just keep on using Edit mode?
