### ISSUE TITLE
AIO and Android widgets?

### ISSUE THREAD

**Issue by mjdjohansson** [zobnin/aio#92]
The long list of AIO widgets at the bottom of the Settings window looks misplaced to me. 

![Screenshot_20231022-201023~2.png](https://github.com/zobnin/aio/assets/121413314/88acfade-2a9d-4669-8678-18a5c18def6b)

I think it would be a good idea to move these widgets into a new menu called 'AIO widgets'. 

And I would also rename the menu 'App widgets' into 'Android widgets'.

I also think it would be interesting if you could show/enable and hide/disable the AIO widgets by checking and unchecking the widget checkboxes, without actually having to open the widget settings.

![Screenshot_20231023-034303~2.png](https://github.com/zobnin/aio/assets/121413314/b5fb13bc-62e5-4b94-85b0-38b82ee6a0b4)

**Comment by zobnin** [comment]
This "new menu" is called side menu :)

**Comment by mjdjohansson** [comment]
Yes, the Side menu is a great way to quickly add widgets to the home screen! It's actually one of my favorite features in AIO :) 

I realize now that my last remark about also making use of the checkboxes was confusing and made it sound like I was only looking for a way to add and hide widgets.

What I was primarily trying to suggest was to declutter the overcrowded Settings window by removing the very long list of Widget settings.

**Comment by zobnin** [comment]
I don't see what the problem is. The settings are intentionally made no more than two levels (so more convenient and less confusing), all widgets are moved to the end of the settings window and are visible only when scrolling. They should not bother you in any way at all.

**Comment by mjdjohansson** [comment]
I think what's really been bothering me is the vague separation between the two groups of settings in the Settings window:

The first group has no title, the second group is called WIDGET SETTINGS.

I think it would be easier to understand the difference between the two groups if the first group also had a title (AIO SETTINGS).

Also, there is no extra space between the first group and the second group, which makes it harder to tell the two apart.

**Comment by mjdjohansson** [comment]
I just feel the layout of the Settings window has room for improvement.

In the current layout there is no strong visual separation between the Widget settings title and the previous menu. This makes the title blend in with the other menus and therefore hard to see. This in turn makes the long list of widgets seem out of place.

![Screenshot_20231030-022450~2.png](https://github.com/zobnin/aio/assets/121413314/ac4ed9aa-2205-4207-b6d4-10bc2c4d9a07)

-------------------
Settings
-------------------
x abc
x abc
WIDGET SETTINGS
x abc
x abc
x abc
x abc
-------------------



Adding a space or line would improve visibility.

-------------------
Settings
-------------------
x abc
x abc

WIDGET SETTINGS
x abc
x abc
x abc
x abc
-------------------



I also think adding a matching title to the first group of settings would emphasize the difference between the two groups. It would also help create a more balanced list structure that is easier to understand.

-------------------
Settings
-------------------
AIO SETTINGS
x abc
x abc

WIDGET SETTINGS
x abc
x abc
x abc
x abc
-------------------
