### ISSUE TITLE
Minimized indicator vs. Notification symbol vs. Folded symbol?

### ISSUE THREAD

**Issue by mjdjohansson** [zobnin/aio#93]
It's possible to change the Minimized indicator to a '+' in the widget header. 
![Screenshot_20231101-000601.png](https://github.com/zobnin/aio/assets/121413314/3471695e-bc8f-4107-a940-357fb86e24aa)

But that doesn't change the equivalent Folded symbol '•' in the top right corner of the widget, when the header is toggled off. This seems a bit inconsistent.
![Screenshot_20231031-225053~2.png](https://github.com/zobnin/aio/assets/121413314/227483cd-af16-4482-b0c8-2dc0073e2870)

Using a '•' symbol instead of the '+' indicator here, is also kind of ambiguous, as this symbol is already used as a notification in the widget header.
![Screenshot_20231031-225029~2.png](https://github.com/zobnin/aio/assets/121413314/38cd2892-3b89-44a1-956a-411a4975c819)

Changing the Minimized indicator to '•' for consistency isn't really a solution.
![Screenshot_20231031-225526.png](https://github.com/zobnin/aio/assets/121413314/9027a3cb-e0be-4d87-bb98-90eae3c05955)

Apart from this, I think it could make sense to swap out the word 'minimized' with 'folded', as this is the term normally used in AIO.
![Screenshot_20231031-223944.png](https://github.com/zobnin/aio/assets/121413314/d68a8f8d-e668-4b8b-a4bb-0c52bfe0d538)

These are only minor details, but maybe still worth mentioning.

**Comment by zobnin** [comment]
I agree that not all of these icons are obvious, but it's too late to change them. Users are used to them.

**Comment by mjdjohansson** [comment]
I don't see your point. Why is it too late to unify the two different minimized indicators? 

Just because users are already used to the discrepancy doesn't sound like a valid argument to me.

**Comment by mjdjohansson** [comment]
In my opinion it would be much more intuitive if it looked like this:

Header ON:
![Screenshot_20231031-225029~2.png](https://github.com/zobnin/aio/assets/121413314/da9d2741-080d-4a16-8bf6-124ea5ff39e0)

Header OFF:
![folded notification .png](https://github.com/zobnin/aio/assets/121413314/2e614a5e-0ec1-4a93-aab2-82e580d66a37)

This would surely be less confusing for new users and I can't see why it should be a problem to anyone else.

**Comment by mjdjohansson** [comment]
This would surely be less confusing to new users and I don't see why existing users should have any problems with it.

**Comment by mjdjohansson** [comment]
Or did I misunderstand you about the users, and you were implying that it's too late to change them, because it's not worth the time and effort to refine smaller details like this?

**Comment by mj-sson** [comment]
I would just like to add that it is possible to replace the '•' folded symbol in your own themes.

You just have to export the theme, replace the "compactModeNoTitleSignCompact" symbol in the file, and then import the file again 😀
