### ISSUE TITLE
Calendar (Day) widget showing wrong times after Daylight Saving Time 

### ISSUE THREAD

**Issue by peaceful-octopus** [zobnin/aio#94]
**Describe the bug**
This morning after Daylight Saving Time ended in the United States, the Calendar (Day) widget is showing the wrong time for events.

**To Reproduce**
1. Use Calendar (Day) widget after Daylight Saving Time ends

**Expected behavior**
The calendar displays the correct time for upcoming events.

**Screenshots**
![Screenshot_20231105_091206_AIO Launcher](https://github.com/zobnin/aio/assets/12649531/8f60a670-e7c6-4436-b914-8d9adb6b7092)
![Screenshot_20231105_091234_Calendar](https://github.com/zobnin/aio/assets/12649531/d38ac8ba-78e9-45d9-bc12-39e6cdd4b9a7)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S22+
 - Android version: Android 13
 - AIO Version: 4.9.3

**Comment by zobnin** [comment]
Thank you for the info. I will fix it in the next version.
For now you can just restart the app.
