### ISSUE TITLE
Rename Apps/Applications menu to Side menu? 

### ISSUE THREAD

**Issue by mj-sson** [zobnin/aio#96]
I think that the terms "Apps menu" and "Applications menu" should be updated to "Side menu" : 

![Screenshot_20231119-023452.png](https://github.com/zobnin/aio/assets/121413314/f7a0ec36-a80b-4239-919f-67c7363d504d)

![Screenshot_20231119-025526.png](https://github.com/zobnin/aio/assets/121413314/b34fd104-2d7b-4c63-8bb5-c992cf030806)

**Comment by zobnin** [comment]
Will be fixed in the next version. Thank you.
