### ISSUE TITLE
Expand the margins around the Color picker? 

### ISSUE THREAD

**Issue by mj-sson** [zobnin/aio#98]
Would it be possible to expand the margins around the Color picker? 

The reason I'm asking is that I seem to be a bit clumsy and often find myself swiping slightly outside of the window, when selecting colors close to the edge. 

This closes the Color picker window and resets the changes you have already made. This can be a bit frustrating when you have carefully selected the right color, brightness and transparency combination and you end up having to start all over again.

Maybe this is just me but I thought I'd ask anyway.

![Screenshot_20231119-224347~2.png](https://github.com/zobnin/aio/assets/121413314/3002a410-39e2-4c6e-912e-414e543f5502)

**Comment by zobnin** [comment]
This is the standard indentation in all dialogs; if I change it, uniformity will be lost. You can easily avoid your issue by first tapping in the middle and then dragging your finger towards the edge, instead of directly tapping on the edge.

**Comment by mj-sson** [comment]
The problem I see with this is, that you can't drag your finger over the edge and lift it outside the dialog. If you do, the dialog is closed.

So without this possibility, I'm afraid I don't see how 'dragging towards the edge' would be much better than 'directly tapping on the edge'?

But maybe it's possible to configure how the dialog is closed? 

OLD: 'press+release outside dialog > close dialog' 

NEW: 'press outside dialog > close dialog'
NEW: 'release outside dialog > ignore'

**Comment by mj-sson** [comment]
Or can you change the behavior of the dialog so that it doesn't close when you;

1. press and hold inside the dialog >
2. while still holding, drag finger out of the dialog >
3. release finger outside the dialog ? 

This should work well with your suggestion of "dragging finger towards the edge".

**Comment by mj-sson** [comment]
The dialog in the Color picker DEMO APP seems to be more forgiving  than the version used in the AIO Launcher. The dialog is slightly larger so maybe that's why it's harder to close this dialog by mistake? 

Would it be possible to increase the overall size of the Color picker dialog used in the AIO Launcher as well?

![Photo_2023-11-21_03-55-53_PM.png](https://github.com/zobnin/aio/assets/121413314/b8658695-1b40-478a-8055-5b39323eb9a0)

**Comment by mj-sson** [comment]
Why can't you just use the same size as the Shortcut > Edit > "Edit color" dialog? 

![Screenshot_20231124-232229~(1)~2.jpg](https://github.com/zobnin/aio/assets/121413314/deae56c3-bd62-4de4-979a-3fcd88ba3d4d)

This larger dialog is more comfortable to use and is more or less foolproof! 

![Photo_2023-11-25_12-13-00_AM.png](https://github.com/zobnin/aio/assets/121413314/3839edba-c67f-4cf0-bf51-abf4ae0514e3)
