### ISSUE TITLE
News feed doesn't refresh

### ISSUE THREAD

**Issue by mammenj** [zobnin/aio#99]
**Describe the bug**
News feed widget doesn't refresh with addition of new feed url

**To Reproduce**
1. Go to news feed widget, add a new feed url
2. Wait for new news content 
3. No new content even after waiting for an hour or a day

**Expected behavior**
New news content to be displayed 

**Smartphone (please complete the following information):**
 - Device: LG thinqs
 - Android version: 10
 - AIO Version: latest 

**Additional context**
It worked fine before the latest update

**Comment by zobnin** [comment]
Works on my side without any problems. Maybe your feed is broken. Give me the link please.

**Comment by zobnin** [comment]
Yes. There is problem when loading more than one feed. Will be fixed. Thank you.
